// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fingerprint_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFingerprintsByStatus = `-- name: CountFingerprintsByStatus :many
SELECT status, COUNT(*) AS count FROM fingerprint_queue GROUP BY status
`

type CountFingerprintsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountFingerprintsByStatus(ctx context.Context) ([]CountFingerprintsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countFingerprintsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFingerprintsByStatusRow{}
	for rows.Next() {
		var i CountFingerprintsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dequeueFingerprint = `-- name: DequeueFingerprint :one
UPDATE fingerprint_queue
SET status = 'processing', updated_at = now()
WHERE id = (
    SELECT id FROM fingerprint_queue
    WHERE status = 'pending'
       OR (status = 'failed' AND retry_count < 3)
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, url, hostname_id, source, status, retry_count, created_at, updated_at
`

func (q *Queries) DequeueFingerprint(ctx context.Context) (FingerprintQueue, error) {
	row := q.db.QueryRow(ctx, dequeueFingerprint)
	var i FingerprintQueue
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.HostnameID,
		&i.Source,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueFingerprint = `-- name: EnqueueFingerprint :one
INSERT INTO fingerprint_queue (url, hostname_id, source)
VALUES ($1, $2, $3)
ON CONFLICT (url, hostname_id) WHERE status IN ('pending', 'processing') DO NOTHING
RETURNING id, url, hostname_id, source, status, retry_count, created_at, updated_at
`

type EnqueueFingerprintParams struct {
	Url        string      `json:"url"`
	HostnameID pgtype.UUID `json:"hostname_id"`
	Source     string      `json:"source"`
}

func (q *Queries) EnqueueFingerprint(ctx context.Context, arg EnqueueFingerprintParams) (FingerprintQueue, error) {
	row := q.db.QueryRow(ctx, enqueueFingerprint, arg.Url, arg.HostnameID, arg.Source)
	var i FingerprintQueue
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.HostnameID,
		&i.Source,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFingerprintDone = `-- name: MarkFingerprintDone :exec
UPDATE fingerprint_queue SET status = 'done', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkFingerprintDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFingerprintDone, id)
	return err
}

const markFingerprintFailed = `-- name: MarkFingerprintFailed :exec
UPDATE fingerprint_queue SET status = 'failed', retry_count = retry_count + 1, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkFingerprintFailed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markFingerprintFailed, id)
	return err
}

const recoverStaleProcessing = `-- name: RecoverStaleProcessing :exec
UPDATE fingerprint_queue
SET status = 'pending', updated_at = now()
WHERE status = 'processing'
  AND updated_at < now() - interval '2 minutes'
`

func (q *Queries) RecoverStaleProcessing(ctx context.Context) error {
	_, err := q.db.Exec(ctx, recoverStaleProcessing)
	return err
}
