// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hostnames.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHostnames = `-- name: CountHostnames :one
SELECT COUNT(*) FROM hostnames
WHERE
    ($1::UUID IS NULL OR wildcard_id = $1) AND
    ($2::hostname_status IS NULL OR status = $2) AND
    ($3::hostname_type IS NULL OR type = $3)
`

type CountHostnamesParams struct {
	WildcardID pgtype.UUID        `json:"wildcard_id"`
	Status     NullHostnameStatus `json:"status"`
	Type       NullHostnameType   `json:"type"`
}

func (q *Queries) CountHostnames(ctx context.Context, arg CountHostnamesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHostnames, arg.WildcardID, arg.Status, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getHostname = `-- name: GetHostname :one
SELECT id, wildcard_id, fqdn, ip, cdn, status, type, dns, ports, last_seen_at, created_at, updated_at FROM hostnames WHERE id = $1
`

func (q *Queries) GetHostname(ctx context.Context, id pgtype.UUID) (Hostname, error) {
	row := q.db.QueryRow(ctx, getHostname, id)
	var i Hostname
	err := row.Scan(
		&i.ID,
		&i.WildcardID,
		&i.Fqdn,
		&i.Ip,
		&i.Cdn,
		&i.Status,
		&i.Type,
		&i.Dns,
		&i.Ports,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHostnameByFQDN = `-- name: GetHostnameByFQDN :one
SELECT id, wildcard_id, fqdn, ip, cdn, status, type, dns, ports, last_seen_at, created_at, updated_at FROM hostnames WHERE fqdn = $1
`

func (q *Queries) GetHostnameByFQDN(ctx context.Context, fqdn string) (Hostname, error) {
	row := q.db.QueryRow(ctx, getHostnameByFQDN, fqdn)
	var i Hostname
	err := row.Scan(
		&i.ID,
		&i.WildcardID,
		&i.Fqdn,
		&i.Ip,
		&i.Cdn,
		&i.Status,
		&i.Type,
		&i.Dns,
		&i.Ports,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHostnames = `-- name: ListHostnames :many
SELECT id, wildcard_id, fqdn, ip, cdn, status, type, ports, last_seen_at, created_at, updated_at
FROM hostnames
WHERE
    ($3::UUID IS NULL OR wildcard_id = $3) AND
    ($4::hostname_status IS NULL OR status = $4) AND
    ($5::hostname_type IS NULL OR type = $5)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListHostnamesParams struct {
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	WildcardID pgtype.UUID        `json:"wildcard_id"`
	Status     NullHostnameStatus `json:"status"`
	Type       NullHostnameType   `json:"type"`
}

type ListHostnamesRow struct {
	ID         pgtype.UUID        `json:"id"`
	WildcardID pgtype.UUID        `json:"wildcard_id"`
	Fqdn       string             `json:"fqdn"`
	Ip         *netip.Addr        `json:"ip"`
	Cdn        pgtype.Text        `json:"cdn"`
	Status     HostnameStatus     `json:"status"`
	Type       HostnameType       `json:"type"`
	Ports      []byte             `json:"ports"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListHostnames(ctx context.Context, arg ListHostnamesParams) ([]ListHostnamesRow, error) {
	rows, err := q.db.Query(ctx, listHostnames,
		arg.Limit,
		arg.Offset,
		arg.WildcardID,
		arg.Status,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHostnamesRow{}
	for rows.Next() {
		var i ListHostnamesRow
		if err := rows.Scan(
			&i.ID,
			&i.WildcardID,
			&i.Fqdn,
			&i.Ip,
			&i.Cdn,
			&i.Status,
			&i.Type,
			&i.Ports,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostnamesByWildcard = `-- name: ListHostnamesByWildcard :many
SELECT id, wildcard_id, fqdn, ip, cdn, status, type, dns, ports, last_seen_at, created_at, updated_at FROM hostnames WHERE wildcard_id = $1 ORDER BY created_at
`

func (q *Queries) ListHostnamesByWildcard(ctx context.Context, wildcardID pgtype.UUID) ([]Hostname, error) {
	rows, err := q.db.Query(ctx, listHostnamesByWildcard, wildcardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hostname{}
	for rows.Next() {
		var i Hostname
		if err := rows.Scan(
			&i.ID,
			&i.WildcardID,
			&i.Fqdn,
			&i.Ip,
			&i.Cdn,
			&i.Status,
			&i.Type,
			&i.Dns,
			&i.Ports,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHostnameLastSeen = `-- name: UpdateHostnameLastSeen :exec
UPDATE hostnames SET last_seen_at = now(), status = 'alive', updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateHostnameLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateHostnameLastSeen, id)
	return err
}

const updateHostnameStatus = `-- name: UpdateHostnameStatus :exec
UPDATE hostnames SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateHostnameStatusParams struct {
	ID     pgtype.UUID    `json:"id"`
	Status HostnameStatus `json:"status"`
}

func (q *Queries) UpdateHostnameStatus(ctx context.Context, arg UpdateHostnameStatusParams) error {
	_, err := q.db.Exec(ctx, updateHostnameStatus, arg.ID, arg.Status)
	return err
}

const upsertHostname = `-- name: UpsertHostname :one
INSERT INTO hostnames (wildcard_id, fqdn, ip, cdn, status, type, dns, ports, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (fqdn) DO UPDATE SET
    ip = EXCLUDED.ip,
    cdn = EXCLUDED.cdn,
    status = EXCLUDED.status,
    type = EXCLUDED.type,
    dns = EXCLUDED.dns,
    ports = EXCLUDED.ports,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
RETURNING id, wildcard_id, fqdn, ip, cdn, status, type, dns, ports, last_seen_at, created_at, updated_at
`

type UpsertHostnameParams struct {
	WildcardID pgtype.UUID        `json:"wildcard_id"`
	Fqdn       string             `json:"fqdn"`
	Ip         *netip.Addr        `json:"ip"`
	Cdn        pgtype.Text        `json:"cdn"`
	Status     HostnameStatus     `json:"status"`
	Type       HostnameType       `json:"type"`
	Dns        []byte             `json:"dns"`
	Ports      []byte             `json:"ports"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) UpsertHostname(ctx context.Context, arg UpsertHostnameParams) (Hostname, error) {
	row := q.db.QueryRow(ctx, upsertHostname,
		arg.WildcardID,
		arg.Fqdn,
		arg.Ip,
		arg.Cdn,
		arg.Status,
		arg.Type,
		arg.Dns,
		arg.Ports,
		arg.LastSeenAt,
	)
	var i Hostname
	err := row.Scan(
		&i.ID,
		&i.WildcardID,
		&i.Fqdn,
		&i.Ip,
		&i.Cdn,
		&i.Status,
		&i.Type,
		&i.Dns,
		&i.Ports,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
