// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type HostnameStatus string

const (
	HostnameStatusAlive       HostnameStatus = "alive"
	HostnameStatusDead        HostnameStatus = "dead"
	HostnameStatusUnreachable HostnameStatus = "unreachable"
)

func (e *HostnameStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HostnameStatus(s)
	case string:
		*e = HostnameStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HostnameStatus: %T", src)
	}
	return nil
}

type NullHostnameStatus struct {
	HostnameStatus HostnameStatus `json:"hostname_status"`
	Valid          bool           `json:"valid"` // Valid is true if HostnameStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHostnameStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HostnameStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HostnameStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHostnameStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HostnameStatus), nil
}

type HostnameType string

const (
	HostnameTypeWeb     HostnameType = "web"
	HostnameTypeOther   HostnameType = "other"
	HostnameTypeUnknown HostnameType = "unknown"
)

func (e *HostnameType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HostnameType(s)
	case string:
		*e = HostnameType(s)
	default:
		return fmt.Errorf("unsupported scan type for HostnameType: %T", src)
	}
	return nil
}

type NullHostnameType struct {
	HostnameType HostnameType `json:"hostname_type"`
	Valid        bool         `json:"valid"` // Valid is true if HostnameType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHostnameType) Scan(value interface{}) error {
	if value == nil {
		ns.HostnameType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HostnameType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHostnameType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HostnameType), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
	JobStatusTimeout   JobStatus = "timeout"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type ReconMode string

const (
	ReconModeNormal    ReconMode = "normal"
	ReconModeIntensive ReconMode = "intensive"
)

func (e *ReconMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReconMode(s)
	case string:
		*e = ReconMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ReconMode: %T", src)
	}
	return nil
}

type NullReconMode struct {
	ReconMode ReconMode `json:"recon_mode"`
	Valid     bool      `json:"valid"` // Valid is true if ReconMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReconMode) Scan(value interface{}) error {
	if value == nil {
		ns.ReconMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReconMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReconMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReconMode), nil
}

type FingerprintQueue struct {
	ID         pgtype.UUID        `json:"id"`
	Url        string             `json:"url"`
	HostnameID pgtype.UUID        `json:"hostname_id"`
	Source     string             `json:"source"`
	Status     string             `json:"status"`
	RetryCount int32              `json:"retry_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Hostname struct {
	ID         pgtype.UUID        `json:"id"`
	WildcardID pgtype.UUID        `json:"wildcard_id"`
	Fqdn       string             `json:"fqdn"`
	Ip         *netip.Addr        `json:"ip"`
	Cdn        pgtype.Text        `json:"cdn"`
	Status     HostnameStatus     `json:"status"`
	Type       HostnameType       `json:"type"`
	Dns        []byte             `json:"dns"`
	Ports      []byte             `json:"ports"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ReconJob struct {
	ID            pgtype.UUID        `json:"id"`
	WildcardID    pgtype.UUID        `json:"wildcard_id"`
	Mode          ReconMode          `json:"mode"`
	Status        JobStatus          `json:"status"`
	ScalewayJobID pgtype.Text        `json:"scaleway_job_id"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WebResult struct {
	ID            pgtype.UUID        `json:"id"`
	HostnameID    pgtype.UUID        `json:"hostname_id"`
	Url           string             `json:"url"`
	Chain         []byte             `json:"chain"`
	Technologies  []byte             `json:"technologies"`
	Cookies       []byte             `json:"cookies"`
	Metadata      []byte             `json:"metadata"`
	ExternalHosts []byte             `json:"external_hosts"`
	ScannedAt     pgtype.Timestamptz `json:"scanned_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Wildcard struct {
	ID                pgtype.UUID        `json:"id"`
	Value             string             `json:"value"`
	Active            bool               `json:"active"`
	LastReconAt       pgtype.Timestamptz `json:"last_recon_at"`
	LastRevalidatedAt pgtype.Timestamptz `json:"last_revalidated_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
