// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recon_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveJobs = `-- name: CountActiveJobs :one
SELECT COUNT(*) FROM recon_jobs WHERE status IN ('pending', 'running')
`

func (q *Queries) CountActiveJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJobs = `-- name: CountJobs :one
SELECT COUNT(*) FROM recon_jobs
WHERE
    ($1::UUID IS NULL OR wildcard_id = $1) AND
    ($2::job_status IS NULL OR status = $2)
`

type CountJobsParams struct {
	WildcardID pgtype.UUID   `json:"wildcard_id"`
	Status     NullJobStatus `json:"status"`
}

func (q *Queries) CountJobs(ctx context.Context, arg CountJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs, arg.WildcardID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJob = `-- name: GetJob :one
SELECT id, wildcard_id, mode, status, scaleway_job_id, started_at, completed_at, created_at FROM recon_jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (ReconJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i ReconJob
	err := row.Scan(
		&i.ID,
		&i.WildcardID,
		&i.Mode,
		&i.Status,
		&i.ScalewayJobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJobCompletionStats = `-- name: GetJobCompletionStats :one
SELECT
    COUNT(h.id) FILTER (WHERE h.created_at >= j.started_at) AS new_hostnames,
    COUNT(h.id) FILTER (WHERE h.status = 'dead' AND h.updated_at >= j.started_at) AS newly_dead,
    COUNT(DISTINCT wr.id) FILTER (WHERE wr.created_at >= j.started_at) AS new_web_services
FROM recon_jobs j
LEFT JOIN hostnames h ON h.wildcard_id = j.wildcard_id
LEFT JOIN web_results wr ON wr.hostname_id = h.id AND wr.created_at >= j.started_at
WHERE j.id = $1
`

type GetJobCompletionStatsRow struct {
	NewHostnames   int64 `json:"new_hostnames"`
	NewlyDead      int64 `json:"newly_dead"`
	NewWebServices int64 `json:"new_web_services"`
}

func (q *Queries) GetJobCompletionStats(ctx context.Context, id pgtype.UUID) (GetJobCompletionStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobCompletionStats, id)
	var i GetJobCompletionStatsRow
	err := row.Scan(&i.NewHostnames, &i.NewlyDead, &i.NewWebServices)
	return i, err
}

const hasActiveJobForWildcard = `-- name: HasActiveJobForWildcard :one
SELECT EXISTS(
    SELECT 1 FROM recon_jobs WHERE wildcard_id = $1 AND status IN ('pending', 'running')
) AS has_active
`

func (q *Queries) HasActiveJobForWildcard(ctx context.Context, wildcardID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveJobForWildcard, wildcardID)
	var has_active bool
	err := row.Scan(&has_active)
	return has_active, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO recon_jobs (wildcard_id, mode, status)
VALUES ($1, $2, 'pending')
RETURNING id, wildcard_id, mode, status, scaleway_job_id, started_at, completed_at, created_at
`

type InsertJobParams struct {
	WildcardID pgtype.UUID `json:"wildcard_id"`
	Mode       ReconMode   `json:"mode"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (ReconJob, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.WildcardID, arg.Mode)
	var i ReconJob
	err := row.Scan(
		&i.ID,
		&i.WildcardID,
		&i.Mode,
		&i.Status,
		&i.ScalewayJobID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, wildcard_id, mode, status, scaleway_job_id, started_at, completed_at, created_at FROM recon_jobs
WHERE
    ($3::UUID IS NULL OR wildcard_id = $3) AND
    ($4::job_status IS NULL OR status = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit      int32         `json:"limit"`
	Offset     int32         `json:"offset"`
	WildcardID pgtype.UUID   `json:"wildcard_id"`
	Status     NullJobStatus `json:"status"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ReconJob, error) {
	rows, err := q.db.Query(ctx, listJobs,
		arg.Limit,
		arg.Offset,
		arg.WildcardID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconJob{}
	for rows.Next() {
		var i ReconJob
		if err := rows.Scan(
			&i.ID,
			&i.WildcardID,
			&i.Mode,
			&i.Status,
			&i.ScalewayJobID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobScalewayID = `-- name: UpdateJobScalewayID :exec
UPDATE recon_jobs SET scaleway_job_id = $2 WHERE id = $1
`

type UpdateJobScalewayIDParams struct {
	ID            pgtype.UUID `json:"id"`
	ScalewayJobID pgtype.Text `json:"scaleway_job_id"`
}

func (q *Queries) UpdateJobScalewayID(ctx context.Context, arg UpdateJobScalewayIDParams) error {
	_, err := q.db.Exec(ctx, updateJobScalewayID, arg.ID, arg.ScalewayJobID)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE recon_jobs SET status = $1::job_status,
    started_at = CASE WHEN $1 = 'running' THEN now() ELSE started_at END,
    completed_at = CASE WHEN $1 IN ('completed', 'failed', 'timeout') THEN now() ELSE completed_at END
WHERE id = $2
`

type UpdateJobStatusParams struct {
	Status JobStatus   `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus, arg.Status, arg.ID)
	return err
}
