// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wildcards.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWildcard = `-- name: DeleteWildcard :exec
DELETE FROM wildcards WHERE id = $1
`

func (q *Queries) DeleteWildcard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWildcard, id)
	return err
}

const getActiveWildcards = `-- name: GetActiveWildcards :many
SELECT id, value, active, last_recon_at, last_revalidated_at, created_at FROM wildcards WHERE active = true ORDER BY created_at
`

func (q *Queries) GetActiveWildcards(ctx context.Context) ([]Wildcard, error) {
	rows, err := q.db.Query(ctx, getActiveWildcards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wildcard{}
	for rows.Next() {
		var i Wildcard
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Active,
			&i.LastReconAt,
			&i.LastRevalidatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWildcard = `-- name: GetWildcard :one
SELECT id, value, active, last_recon_at, last_revalidated_at, created_at FROM wildcards WHERE id = $1
`

func (q *Queries) GetWildcard(ctx context.Context, id pgtype.UUID) (Wildcard, error) {
	row := q.db.QueryRow(ctx, getWildcard, id)
	var i Wildcard
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Active,
		&i.LastReconAt,
		&i.LastRevalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWildcard = `-- name: InsertWildcard :one
INSERT INTO wildcards (value) VALUES ($1) RETURNING id, value, active, last_recon_at, last_revalidated_at, created_at
`

func (q *Queries) InsertWildcard(ctx context.Context, value string) (Wildcard, error) {
	row := q.db.QueryRow(ctx, insertWildcard, value)
	var i Wildcard
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Active,
		&i.LastReconAt,
		&i.LastRevalidatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWildcards = `-- name: ListWildcards :many
SELECT w.id, w.value, w.active, w.last_recon_at, w.last_revalidated_at, w.created_at,
    COUNT(h.id) AS hostnames_total,
    COUNT(h.id) FILTER (WHERE h.status = 'alive') AS hostnames_alive,
    COUNT(h.id) FILTER (WHERE h.status = 'dead') AS hostnames_dead,
    COUNT(h.id) FILTER (WHERE h.status = 'unreachable') AS hostnames_unreachable,
    COUNT(h.id) FILTER (WHERE h.type = 'web') AS web_services
FROM wildcards w
LEFT JOIN hostnames h ON h.wildcard_id = w.id
GROUP BY w.id
ORDER BY w.created_at DESC
`

type ListWildcardsRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Value                string             `json:"value"`
	Active               bool               `json:"active"`
	LastReconAt          pgtype.Timestamptz `json:"last_recon_at"`
	LastRevalidatedAt    pgtype.Timestamptz `json:"last_revalidated_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	HostnamesTotal       int64              `json:"hostnames_total"`
	HostnamesAlive       int64              `json:"hostnames_alive"`
	HostnamesDead        int64              `json:"hostnames_dead"`
	HostnamesUnreachable int64              `json:"hostnames_unreachable"`
	WebServices          int64              `json:"web_services"`
}

func (q *Queries) ListWildcards(ctx context.Context) ([]ListWildcardsRow, error) {
	rows, err := q.db.Query(ctx, listWildcards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWildcardsRow{}
	for rows.Next() {
		var i ListWildcardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Active,
			&i.LastReconAt,
			&i.LastRevalidatedAt,
			&i.CreatedAt,
			&i.HostnamesTotal,
			&i.HostnamesAlive,
			&i.HostnamesDead,
			&i.HostnamesUnreachable,
			&i.WebServices,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastReconAt = `-- name: UpdateLastReconAt :exec
UPDATE wildcards SET last_recon_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastReconAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastReconAt, id)
	return err
}

const updateLastRevalidatedAt = `-- name: UpdateLastRevalidatedAt :exec
UPDATE wildcards SET last_revalidated_at = now() WHERE id = $1
`

func (q *Queries) UpdateLastRevalidatedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastRevalidatedAt, id)
	return err
}
