// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: console.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProgramAssets = `-- name: CountProgramAssets :many
SELECT c.program_id,
       count(*)::int AS assets,
       count(*) FILTER (WHERE c.scope_status = 'in_scope')::int AS in_scope
  FROM asset_current c
 WHERE c.org_id = $1::uuid
   AND c.lifecycle <> 'archived'
 GROUP BY c.program_id
`

type CountProgramAssetsParams struct {
	OrgID pgtype.UUID
}

type CountProgramAssetsRow struct {
	ProgramID pgtype.UUID
	Assets    int32
	InScope   int32
}

// CountProgramAssets is the aggregation the list only runs when asked.
//
// One statement over the whole tenant rather than one per program, grouped
// here. Ten programs would otherwise be ten scans of the projection for a
// number that sits beside a name.
//
// @tenant: scoped
func (q *Queries) CountProgramAssets(ctx context.Context, arg CountProgramAssetsParams) ([]CountProgramAssetsRow, error) {
	rows, err := q.db.Query(ctx, countProgramAssets, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountProgramAssetsRow{}
	for rows.Next() {
		var i CountProgramAssetsRow
		if err := rows.Scan(&i.ProgramID, &i.Assets, &i.InScope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO program (id, org_id, name, platform, platform_ref,
                     authorized_from, authorized_to, authorization_ref,
                     rate_limit_rps, discovery_interval, state, created_by, updated_by)
VALUES ($1::uuid, $2::uuid, $3::text,
        $4::text, $5::text,
        $6::timestamptz, $7::timestamptz,
        $8::text,
        $9::int, $10::interval, $11::text,
        $12::uuid, $12::uuid)
RETURNING id, name, platform, platform_ref, state,
          authorized_from, authorized_to, authorization_ref,
          rate_limit_rps, discovery_interval, last_discovery_at,
          version, created_at, updated_at
`

type CreateProgramParams struct {
	ProgramID         pgtype.UUID
	OrgID             pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	State             string
	Actor             pgtype.UUID
}

type CreateProgramRow struct {
	ID                pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// CreateProgram opens a perimeter.
//
// No version travels in, because there is nothing to avoid overwriting.
//
// @tenant: scoped
func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (CreateProgramRow, error) {
	row := q.db.QueryRow(ctx, createProgram,
		arg.ProgramID,
		arg.OrgID,
		arg.Name,
		arg.Platform,
		arg.PlatformRef,
		arg.AuthorizedFrom,
		arg.AuthorizedTo,
		arg.AuthorizationRef,
		arg.RateLimitRps,
		arg.DiscoveryInterval,
		arg.State,
		arg.Actor,
	)
	var i CreateProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.PlatformRef,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
		&i.AuthorizationRef,
		&i.RateLimitRps,
		&i.DiscoveryInterval,
		&i.LastDiscoveryAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRule = `-- name: CreateRule :one
INSERT INTO scope_rule (id, org_id, program_id, kind, matcher, pattern,
                        valid_from, valid_to, note, created_by, updated_by)
VALUES ($1::uuid, $2::uuid, $3::uuid,
        $4::text, $5::text, $6::text,
        $7::timestamptz, $8::timestamptz,
        $9::text, $10::uuid, $10::uuid)
RETURNING id, kind, matcher, pattern, valid_from, valid_to, note, version, created_at
`

type CreateRuleParams struct {
	RuleID    pgtype.UUID
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Kind      string
	Matcher   string
	Pattern   string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	Note      *string
	Actor     pgtype.UUID
}

type CreateRuleRow struct {
	ID        pgtype.UUID
	Kind      string
	Matcher   string
	Pattern   string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	Note      *string
	Version   int32
	CreatedAt pgtype.Timestamptz
}

// CreateRule opens one.
//
// @tenant: scoped
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (CreateRuleRow, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.RuleID,
		arg.OrgID,
		arg.ProgramID,
		arg.Kind,
		arg.Matcher,
		arg.Pattern,
		arg.ValidFrom,
		arg.ValidTo,
		arg.Note,
		arg.Actor,
	)
	var i CreateRuleRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Matcher,
		&i.Pattern,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT p.id, p.name, p.platform, p.platform_ref, p.state,
       p.authorized_from, p.authorized_to, p.authorization_ref,
       p.rate_limit_rps, p.discovery_interval, p.last_discovery_at,
       p.version, p.created_at, p.updated_at
  FROM program p
 WHERE p.org_id = $1::uuid AND p.id = $2::uuid
`

type GetProgramParams struct {
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
}

type GetProgramRow struct {
	ID                pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// GetProgram reads one, for the screen that edits it.
//
// @tenant: scoped
func (q *Queries) GetProgram(ctx context.Context, arg GetProgramParams) (GetProgramRow, error) {
	row := q.db.QueryRow(ctx, getProgram, arg.OrgID, arg.ProgramID)
	var i GetProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.PlatformRef,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
		&i.AuthorizationRef,
		&i.RateLimitRps,
		&i.DiscoveryInterval,
		&i.LastDiscoveryAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many

SELECT p.id, p.name, p.platform, p.platform_ref, p.state,
       p.authorized_from, p.authorized_to, p.authorization_ref,
       p.rate_limit_rps, p.discovery_interval, p.last_discovery_at,
       p.version, p.created_at, p.updated_at,
       -- The rules in force, counted against an instant the caller supplies.
       -- valid_to is written by the application and now() is the database's
       -- clock, so comparing the two would make the answer depend on two clocks
       -- agreeing, and a rule closed a moment ago would read as still in force
       -- for the width of the gap.
       (SELECT count(*) FROM scope_rule r
         WHERE r.program_id = p.id
           AND r.valid_from <= $1::timestamptz
           AND (r.valid_to IS NULL OR r.valid_to > $1::timestamptz))::int AS rules_in_force
  FROM program p
 WHERE p.org_id = $2::uuid
 ORDER BY p.name
`

type ListProgramsParams struct {
	At    pgtype.Timestamptz
	OrgID pgtype.UUID
}

type ListProgramsRow struct {
	ID                pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RulesInForce      int32
}

// The console's own reads and writes: perimeters, rules, and the queue.
//
// Everything the console asks about the inventory itself is the search layer's,
// which compiles a tree rather than answering a named query. What is left here
// is the surface that has no filter tree behind it: a program is not a filter,
// and neither is "why is nothing moving".
// ListPrograms is the switcher and the programs screen.
//
// Without the counters, which is the default shape on purpose: the switcher
// sits on every page, and an aggregation over asset_current per program is the
// only thing in this file that costs a scan. They are asked for, not given.
//
// @tenant: scoped
func (q *Queries) ListPrograms(ctx context.Context, arg ListProgramsParams) ([]ListProgramsRow, error) {
	rows, err := q.db.Query(ctx, listPrograms, arg.At, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramsRow{}
	for rows.Next() {
		var i ListProgramsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Platform,
			&i.PlatformRef,
			&i.State,
			&i.AuthorizedFrom,
			&i.AuthorizedTo,
			&i.AuthorizationRef,
			&i.RateLimitRps,
			&i.DiscoveryInterval,
			&i.LastDiscoveryAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RulesInForce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT r.id, r.kind, r.matcher, r.pattern, r.valid_from, r.valid_to, r.note,
       r.version, r.created_at,
       (r.valid_from <= $1::timestamptz
        AND (r.valid_to IS NULL OR r.valid_to > $1::timestamptz)) AS in_force
  FROM scope_rule r
 WHERE r.org_id = $2::uuid AND r.program_id = $3::uuid
 ORDER BY r.valid_to NULLS FIRST, r.created_at DESC
`

type ListRulesParams struct {
	At        pgtype.Timestamptz
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
}

type ListRulesRow struct {
	ID        pgtype.UUID
	Kind      string
	Matcher   string
	Pattern   string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	Note      *string
	Version   int32
	CreatedAt pgtype.Timestamptz
	InForce   *bool
}

// ListRules reads a program's rules, closed ones included.
//
// Closed ones included, because a rule has a period of validity rather than an
// existence: an asset classified out of scope by a rule since closed stays
// explainable, and a screen that hid them would take the answer away.
//
// @tenant: scoped
func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]ListRulesRow, error) {
	rows, err := q.db.Query(ctx, listRules, arg.At, arg.OrgID, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRulesRow{}
	for rows.Next() {
		var i ListRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Matcher,
			&i.Pattern,
			&i.ValidFrom,
			&i.ValidTo,
			&i.Note,
			&i.Version,
			&i.CreatedAt,
			&i.InForce,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueDepth = `-- name: QueueDepth :many
WITH held AS (
    SELECT DISTINCT t.asset_id
      FROM run_target t
      JOIN run r ON r.id = t.run_id
     WHERE r.org_id = $2::uuid
       AND r.state IN ('pending', 'running')
), slots AS (
    SELECT c.program_id, 'resolve' AS queue, c.next_resolve_at AS due_at, c.asset_id
      FROM asset_current c WHERE c.org_id = $2::uuid AND c.next_resolve_at IS NOT NULL
    UNION ALL
    SELECT c.program_id, 'full', c.next_full_at, c.asset_id
      FROM asset_current c WHERE c.org_id = $2::uuid AND c.next_full_at IS NOT NULL
    UNION ALL
    SELECT c.program_id, 'fingerprint', c.next_fingerprint_at, c.asset_id
      FROM asset_current c WHERE c.org_id = $2::uuid AND c.next_fingerprint_at IS NOT NULL
)
SELECT s.program_id, s.queue,
       count(*) FILTER (
           WHERE s.due_at <= $1::timestamptz AND h.asset_id IS NULL)::int AS due,
       count(*) FILTER (WHERE s.due_at > $1::timestamptz)::int AS later,
       count(*) FILTER (WHERE h.asset_id IS NOT NULL)::int AS in_run
  FROM slots s
  LEFT JOIN held h ON h.asset_id = s.asset_id
 GROUP BY 1, 2
`

type QueueDepthParams struct {
	At    pgtype.Timestamptz
	OrgID pgtype.UUID
}

type QueueDepthRow struct {
	ProgramID pgtype.UUID
	Queue     string
	Due       int32
	Later     int32
	InRun     int32
}

// QueueDepth answers "why is nothing moving".
//
// Three numbers per program and per queue, and they are disjoint: a row held by
// a run is not also due. Rows with no due date are counted nowhere, and that is
// the only choice that does not lie, since a null is how a row leaves the
// scheduler. Filing them under later would show a queue that never drains.
//
// The queues are the due date columns rather than the observation layers. There
// are three schedules and four layers, and naming them after the layers would
// promise a tcp queue that does not exist.
//
// @tenant: scoped
func (q *Queries) QueueDepth(ctx context.Context, arg QueueDepthParams) ([]QueueDepthRow, error) {
	rows, err := q.db.Query(ctx, queueDepth, arg.At, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueDepthRow{}
	for rows.Next() {
		var i QueueDepthRow
		if err := rows.Scan(
			&i.ProgramID,
			&i.Queue,
			&i.Due,
			&i.Later,
			&i.InRun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentRuns = `-- name: RecentRuns :many
SELECT r.id, r.program_id, r.kind, r.scope, r.state, r.deadline,
       r.created_at, r.started_at, r.finished_at, r.target_count, r.error,
       -- Two spellings and a zero. The summary gained json tags when the queue
       -- view started reading it back, so a run recorded before that carries
       -- the Go identifier instead. Reading only the tagged key would show
       -- every older run at zero observations, which the COALESCE would then
       -- make indistinguishable from a run that delivered nothing. And a run
       -- that has not delivered has no summary at all, where a null would be
       -- scanned as an error rather than as zero.
       COALESCE((r.summary ->> 'observations')::int,
                (r.summary ->> 'Observations')::int, 0)::int AS observations
  FROM run r
 WHERE r.org_id = $1::uuid
 ORDER BY r.created_at DESC
 LIMIT $2::int
`

type RecentRunsParams struct {
	OrgID pgtype.UUID
	Batch int32
}

type RecentRunsRow struct {
	ID           pgtype.UUID
	ProgramID    pgtype.UUID
	Kind         string
	Scope        string
	State        string
	Deadline     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	TargetCount  *int32
	Error        *string
	Observations int32
}

// RecentRuns is the other half of the answer.
//
// Without them an empty queue and a full one look alike: in both cases the
// screen shows a number and nobody knows whether anything is running.
//
// @tenant: scoped
func (q *Queries) RecentRuns(ctx context.Context, arg RecentRunsParams) ([]RecentRunsRow, error) {
	rows, err := q.db.Query(ctx, recentRuns, arg.OrgID, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentRunsRow{}
	for rows.Next() {
		var i RecentRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Kind,
			&i.Scope,
			&i.State,
			&i.Deadline,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.TargetCount,
			&i.Error,
			&i.Observations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProgram = `-- name: UpdateProgram :one
UPDATE program
   SET name              = $1::text,
       platform          = $2::text,
       platform_ref      = $3::text,
       authorized_from   = $4::timestamptz,
       authorized_to     = $5::timestamptz,
       authorization_ref = $6::text,
       rate_limit_rps    = $7::int,
       discovery_interval = $8::interval,
       state             = $9::text,
       version           = version + 1,
       updated_by        = $10::uuid,
       updated_at        = $11::timestamptz
 WHERE org_id = $12::uuid
   AND id = $13::uuid
   AND version = $14::int
RETURNING id, name, platform, platform_ref, state,
          authorized_from, authorized_to, authorization_ref,
          rate_limit_rps, discovery_interval, last_discovery_at,
          version, created_at, updated_at
`

type UpdateProgramParams struct {
	Name              string
	Platform          *string
	PlatformRef       *string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	State             string
	Actor             pgtype.UUID
	At                pgtype.Timestamptz
	OrgID             pgtype.UUID
	ProgramID         pgtype.UUID
	Version           int32
}

type UpdateProgramRow struct {
	ID                pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

// UpdateProgram edits one, and refuses a stale version by returning no row.
//
// The refusal is the absence of a row rather than a check the caller ran first.
// A read then a write is two statements a concurrent writer can slip between,
// and the whole point of the column is that two writes losing each other
// silently is a lost scope, therefore a scan outside the perimeter.
//
// @tenant: scoped
func (q *Queries) UpdateProgram(ctx context.Context, arg UpdateProgramParams) (UpdateProgramRow, error) {
	row := q.db.QueryRow(ctx, updateProgram,
		arg.Name,
		arg.Platform,
		arg.PlatformRef,
		arg.AuthorizedFrom,
		arg.AuthorizedTo,
		arg.AuthorizationRef,
		arg.RateLimitRps,
		arg.DiscoveryInterval,
		arg.State,
		arg.Actor,
		arg.At,
		arg.OrgID,
		arg.ProgramID,
		arg.Version,
	)
	var i UpdateProgramRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Platform,
		&i.PlatformRef,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
		&i.AuthorizationRef,
		&i.RateLimitRps,
		&i.DiscoveryInterval,
		&i.LastDiscoveryAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRule = `-- name: UpdateRule :one
UPDATE scope_rule
   -- COALESCE on both, because closing a rule is not restating it. A caller
   -- that had to send them back to set valid_to would be one round trip away
   -- from rewriting a rule it only meant to close, and the note is the half
   -- that matters: it is the explanation a closed rule exists to preserve, so
   -- erasing it on the way out takes away exactly what "a rule has a period of
   -- validity rather than an existence" was for.
   --
   -- The consequence, said rather than discovered: a note cannot be cleared
   -- through this statement, only replaced. Nothing asks to today.
   SET pattern    = COALESCE($1::text, pattern),
       note       = COALESCE($2::text, note),
       valid_to   = $3::timestamptz,
       version    = version + 1,
       updated_by = $4::uuid
 WHERE org_id = $5::uuid
   AND program_id = $6::uuid
   AND id = $7::uuid
   AND version = $8::int
RETURNING id, kind, matcher, pattern, valid_from, valid_to, note, version, created_at
`

type UpdateRuleParams struct {
	Pattern   *string
	Note      *string
	ValidTo   pgtype.Timestamptz
	Actor     pgtype.UUID
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	RuleID    pgtype.UUID
	Version   int32
}

type UpdateRuleRow struct {
	ID        pgtype.UUID
	Kind      string
	Matcher   string
	Pattern   string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	Note      *string
	Version   int32
	CreatedAt pgtype.Timestamptz
}

// UpdateRule edits or closes one, and refuses a stale version the same way.
//
// Closing is setting valid_to, never a DELETE. There is no delete statement in
// this file at all, which is stronger than a convention: a statement that does
// not exist cannot be called by a client written in a hurry.
//
// @tenant: scoped
func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (UpdateRuleRow, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.Pattern,
		arg.Note,
		arg.ValidTo,
		arg.Actor,
		arg.OrgID,
		arg.ProgramID,
		arg.RuleID,
		arg.Version,
	)
	var i UpdateRuleRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Matcher,
		&i.Pattern,
		&i.ValidFrom,
		&i.ValidTo,
		&i.Note,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}
