// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlcgen

import (
	"context"
)

// iteratorForAddRunTargets implements pgx.CopyFromSource.
type iteratorForAddRunTargets struct {
	rows                 []AddRunTargetsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddRunTargets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddRunTargets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].AssetID,
		r.rows[0].OrgID,
		r.rows[0].Key,
	}, nil
}

func (r iteratorForAddRunTargets) Err() error {
	return nil
}

// AddRunTargets freezes the list in one round trip.
//
// The copy path rather than a statement per target: a batch is hundreds of
// rows, and a run that costs five hundred round trips to define is one nobody
// will let the scheduler start often.
func (q *Queries) AddRunTargets(ctx context.Context, arg []AddRunTargetsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_target"}, []string{"run_id", "asset_id", "org_id", "key"}, &iteratorForAddRunTargets{rows: arg})
}
