// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ct.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const apexCoverage = `-- name: ApexCoverage :many
SELECT apex, watched_since, san_count, wildcard_count, dropped,
       last_san_at, last_wildcard_at
  FROM ct_apex
 WHERE program_id = $1::uuid
 ORDER BY apex
`

type ApexCoverageParams struct {
	ProgramID pgtype.UUID
}

type ApexCoverageRow struct {
	Apex           string
	WatchedSince   pgtype.Timestamptz
	SanCount       int64
	WildcardCount  int64
	Dropped        int64
	LastSanAt      pgtype.Timestamptz
	LastWildcardAt pgtype.Timestamptz
}

// ApexCoverage is what a programme's Certificate Transparency panel reads.
//
// Counters since the apex was first watched, never over a rolling window, which
// is what watched_since is for: an apex added yesterday and silent is not the
// same finding as one watched for a month and silent, and a window would report
// them identically.
//
// No score. What comes back are the numbers and the span they cover, because a
// coverage confidence collapsed into one figure is the composite score the
// console is built without, and the same argument applies: the reader can tell
// "no certificate in thirty days" from "watched since this morning" and a single
// number cannot.
//
// @tenant: keyed
func (q *Queries) ApexCoverage(ctx context.Context, arg ApexCoverageParams) ([]ApexCoverageRow, error) {
	rows, err := q.db.Query(ctx, apexCoverage, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApexCoverageRow{}
	for rows.Next() {
		var i ApexCoverageRow
		if err := rows.Scan(
			&i.Apex,
			&i.WatchedSince,
			&i.SanCount,
			&i.WildcardCount,
			&i.Dropped,
			&i.LastSanAt,
			&i.LastWildcardAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const apexSet = `-- name: ApexSet :many
SELECT p.org_id, p.id AS program_id, r.pattern AS apex
  FROM scope_rule r
  JOIN program p ON p.id = r.program_id
 WHERE r.kind = 'include'
   AND r.matcher = 'apex'
   AND r.valid_from <= $1
   AND (r.valid_to IS NULL OR r.valid_to > $1)
   AND p.state = 'active'
   AND p.authorized_from <= $1
   AND (p.authorized_to IS NULL OR p.authorized_to > $1)
 ORDER BY p.id, r.pattern
`

type ApexSetParams struct {
	At pgtype.Timestamptz
}

type ApexSetRow struct {
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Apex      string
}

// ApexSet is what the Certificate Transparency matcher walks.
//
// Apex include rules alone. An fqdn rule already declared its host, so the
// asset exists and carries a due date and this stream would find the same name
// and create nothing; putting it in the set would buy a lookup per certificate
// for a row that is already there. cidr and regex never named a thing at all.
//
// The authorization window is here and not only p.state, which is the same two
// lines the discovery cadence carries and for the same reason one level
// earlier: an expired programme left in the set keeps creating assets with due
// dates on a perimeter nobody may scan, so the first thing each one does is
// have its run refused.
//
// The instant is a parameter rather than now(), because valid_to and
// authorized_to are written by the application: comparing them against the
// database's clock would make the answer depend on two clocks agreeing.
//
// @tenant: cross-org
// @why: the apex set spans every tenant by construction. One socket serves the
//
//	whole deployment, and this is the query that decides which organization
//	a name belongs to, so it cannot be filtered by one.
func (q *Queries) ApexSet(ctx context.Context, arg ApexSetParams) ([]ApexSetRow, error) {
	rows, err := q.db.Query(ctx, apexSet, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApexSetRow{}
	for rows.Next() {
		var i ApexSetRow
		if err := rows.Scan(&i.OrgID, &i.ProgramID, &i.Apex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpApexCounters = `-- name: BumpApexCounters :exec
INSERT INTO ct_apex (org_id, program_id, apex, watched_since, san_count, wildcard_count,
                     dropped, last_san_at, last_wildcard_at)
SELECT ($1::uuid[])[i], ($2::uuid[])[i], ($3::text[])[i], $4::timestamptz,
       ($5::bigint[])[i], ($6::bigint[])[i], ($7::bigint[])[i],
       CASE WHEN ($5::bigint[])[i] > 0 THEN $4::timestamptz END,
       CASE WHEN ($6::bigint[])[i] > 0 THEN $4::timestamptz END
  FROM generate_subscripts($3::text[], 1) AS i
ON CONFLICT (program_id, apex) DO UPDATE
   SET san_count        = ct_apex.san_count + excluded.san_count,
       wildcard_count   = ct_apex.wildcard_count + excluded.wildcard_count,
       dropped          = ct_apex.dropped + excluded.dropped,
       last_san_at      = GREATEST(ct_apex.last_san_at, excluded.last_san_at),
       last_wildcard_at = GREATEST(ct_apex.last_wildcard_at, excluded.last_wildcard_at)
`

type BumpApexCountersParams struct {
	OrgIds     []pgtype.UUID
	ProgramIds []pgtype.UUID
	Apexes     []string
	At         pgtype.Timestamptz
	Sans       []int64
	Wildcards  []int64
	Dropped    []int64
}

// BumpApexCounters records what the stream delivered under each apex.
//
// Parallel arrays for the same reason AddRunTargets uses them: one round trip,
// and no COPY on a table carrying a policy. A flush covers every tenant at
// once, so the organization is a column here rather than a scalar.
//
// The insert is what creates the row, so watched_since is set the first time an
// apex is seen rather than by a separate pass. The counters only ever move
// upwards, and the two timestamps take the greatest rather than the newest
// write: a flush is not ordered against another flush.
//
// @tenant: cross-org
// @why: one flush covers every programme in the set, which is what makes it one
//
//	round trip instead of one per tenant.
func (q *Queries) BumpApexCounters(ctx context.Context, arg BumpApexCountersParams) error {
	_, err := q.db.Exec(ctx, bumpApexCounters,
		arg.OrgIds,
		arg.ProgramIds,
		arg.Apexes,
		arg.At,
		arg.Sans,
		arg.Wildcards,
		arg.Dropped,
	)
	return err
}

const feedUptime = `-- name: FeedUptime :one
SELECT count(*)::bigint AS minutes, coalesce(sum(frames), 0)::bigint AS frames
  FROM ct_feed_minute
 WHERE minute >= date_trunc('minute', $1::timestamptz)
`

type FeedUptimeParams struct {
	Since pgtype.Timestamptz
}

type FeedUptimeRow struct {
	Minutes int64
	Frames  int64
}

// FeedUptime is how much of a span the feed was actually alive for.
//
// Without it an apex that delivered nothing and a feed that was down read the
// same, and the second is this deployment's problem rather than a fact about
// the logs. Presence is counted rather than absence inferred, so a minute
// missing from this table is a minute nothing arrived in.
//
// @tenant: none
func (q *Queries) FeedUptime(ctx context.Context, arg FeedUptimeParams) (FeedUptimeRow, error) {
	row := q.db.QueryRow(ctx, feedUptime, arg.Since)
	var i FeedUptimeRow
	err := row.Scan(&i.Minutes, &i.Frames)
	return i, err
}

const forgetApexesOutsideTheSet = `-- name: ForgetApexesOutsideTheSet :execrows
DELETE FROM ct_apex
 WHERE NOT EXISTS (
       SELECT 1
         FROM generate_subscripts($1::text[], 1) AS i
        WHERE ($2::uuid[])[i] = ct_apex.program_id
          AND ($1::text[])[i] = ct_apex.apex)
`

type ForgetApexesOutsideTheSetParams struct {
	Apexes     []string
	ProgramIds []pgtype.UUID
}

// ForgetApexesOutsideTheSet drops the counters of an apex nobody watches now.
//
// watched_since would otherwise span a period during which nothing was
// watching, so an apex removed and put back would read as continuously covered.
// The counts go with it, which is acceptable for the same reason the flush may
// lose a minute: this is a metric and not the journal.
//
// @tenant: cross-org
// @why: it reconciles the whole table against the whole set, in one statement.
func (q *Queries) ForgetApexesOutsideTheSet(ctx context.Context, arg ForgetApexesOutsideTheSetParams) (int64, error) {
	result, err := q.db.Exec(ctx, forgetApexesOutsideTheSet, arg.Apexes, arg.ProgramIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeFeedMinutes = `-- name: PurgeFeedMinutes :execrows
DELETE FROM ct_feed_minute WHERE minute < $1::timestamptz
`

type PurgeFeedMinutesParams struct {
	Before pgtype.Timestamptz
}

// PurgeFeedMinutes bounds the feed's own record.
//
// One row a minute is half a million a year, which is small and unbounded, and
// unbounded is the half that matters: nothing else in this schema grows forever
// and the coverage reading never looks back further than an apex has been
// watched. A delete rather than a partition, because the table is one column
// wide and the window is a comparison.
//
// @tenant: none
func (q *Queries) PurgeFeedMinutes(ctx context.Context, arg PurgeFeedMinutesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeFeedMinutes, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordFeedMinute = `-- name: RecordFeedMinute :exec
INSERT INTO ct_feed_minute (minute, frames)
VALUES (date_trunc('minute', $1::timestamptz), $2::bigint)
ON CONFLICT (minute) DO UPDATE
   SET frames = ct_feed_minute.frames + excluded.frames
`

type RecordFeedMinuteParams struct {
	At     pgtype.Timestamptz
	Frames int64
}

// RecordFeedMinute says the feed was alive for this minute.
//
// Presence rather than absence. A process that dies writes no minute, so a gap
// needs nothing to notice it and no reconciliation after a restart, where
// inferring an outage from its edges would need the loop to survive the thing
// it is recording.
//
// @tenant: none
func (q *Queries) RecordFeedMinute(ctx context.Context, arg RecordFeedMinuteParams) error {
	_, err := q.db.Exec(ctx, recordFeedMinute, arg.At, arg.Frames)
	return err
}

const watchApexes = `-- name: WatchApexes :exec
INSERT INTO ct_apex (org_id, program_id, apex, watched_since)
SELECT ($1::uuid[])[i], ($2::uuid[])[i], ($3::text[])[i], $4::timestamptz
  FROM generate_subscripts($3::text[], 1) AS i
ON CONFLICT (program_id, apex) DO NOTHING
`

type WatchApexesParams struct {
	OrgIds     []pgtype.UUID
	ProgramIds []pgtype.UUID
	Apexes     []string
	At         pgtype.Timestamptz
}

// WatchApexes creates a row for every apex in the set, counting nothing.
//
// Without it an apex that has never produced a SAN has no row, and "watched
// since, delivered nothing" reads identically to "not watched at all". That is
// the difference the coverage reading exists to state.
//
// @tenant: cross-org
// @why: the set spans every tenant, and so does the row it keeps per apex.
func (q *Queries) WatchApexes(ctx context.Context, arg WatchApexesParams) error {
	_, err := q.db.Exec(ctx, watchApexes,
		arg.OrgIds,
		arg.ProgramIds,
		arg.Apexes,
		arg.At,
	)
	return err
}
