// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package sqlcgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRunTarget = `-- name: AddRunTarget :exec
INSERT INTO run_target (run_id, asset_id, org_id, key)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::text)
ON CONFLICT (run_id, asset_id) DO NOTHING
`

type AddRunTargetParams struct {
	RunID   pgtype.UUID
	AssetID pgtype.UUID
	OrgID   pgtype.UUID
	Key     string
}

func (q *Queries) AddRunTarget(ctx context.Context, arg AddRunTargetParams) error {
	_, err := q.db.Exec(ctx, addRunTarget,
		arg.RunID,
		arg.AssetID,
		arg.OrgID,
		arg.Key,
	)
	return err
}

const applyScopeStatus = `-- name: ApplyScopeStatus :exec
WITH updated AS (
    UPDATE asset SET scope_status = $1::text
     WHERE id = $4::uuid
    RETURNING id
)
UPDATE asset_current SET
    scope_status = $1::text,
    next_resolve_at = CASE WHEN $1::text = 'in_scope'
                           THEN COALESCE(next_resolve_at, $2::timestamptz) END,
    next_full_at    = CASE WHEN $1::text = 'in_scope'
                           THEN COALESCE(next_full_at, $3::timestamptz) END,
    next_fingerprint_at = CASE WHEN $1::text = 'in_scope'
                               THEN next_fingerprint_at END
 WHERE asset_id = (SELECT id FROM updated)
`

type ApplyScopeStatusParams struct {
	ScopeStatus   string
	NextResolveAt pgtype.Timestamptz
	NextFullAt    pgtype.Timestamptz
	AssetID       pgtype.UUID
}

// ApplyScopeStatus moves one asset and its schedule together.
//
// The two have to move in the same statement. An asset that should be out but
// keeps its due dates goes on being scanned outside the authorization, and one
// that should be in but has none costs coverage. Writing the rule and then
// reclassifying in two transactions leaves a window where the system scans
// what was just taken away from it.
func (q *Queries) ApplyScopeStatus(ctx context.Context, arg ApplyScopeStatusParams) error {
	_, err := q.db.Exec(ctx, applyScopeStatus,
		arg.ScopeStatus,
		arg.NextResolveAt,
		arg.NextFullAt,
		arg.AssetID,
	)
	return err
}

const clearGenericPivots = `-- name: ClearGenericPivots :exec
DELETE FROM generic_pivot_value
`

// ReplaceGenericPivots is the whole of the seed's write.
//
// Replacement rather than merge: a merge would let an entry added outside the
// repository survive every deployment, and the divergence would be invisible.
func (q *Queries) ClearGenericPivots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearGenericPivots)
	return err
}

const closeRun = `-- name: CloseRun :exec
UPDATE run SET
    state       = $1::text,
    started_at  = COALESCE(started_at, $2::timestamptz),
    finished_at = $2::timestamptz,
    summary     = $3::jsonb,
    error       = $4::text
 WHERE id = $5::uuid
`

type CloseRunParams struct {
	State   string
	At      pgtype.Timestamptz
	Summary []byte
	Error   *string
	RunID   pgtype.UUID
}

// CloseRun records what a run did.
//
// started_at is written by the first report and never moved afterwards: it is
// the only thing that separates a run something actually opened from one whose
// provisioning failed, and those two call for opposite actions.
func (q *Queries) CloseRun(ctx context.Context, arg CloseRunParams) error {
	_, err := q.db.Exec(ctx, closeRun,
		arg.State,
		arg.At,
		arg.Summary,
		arg.Error,
		arg.RunID,
	)
	return err
}

const countObservations = `-- name: CountObservations :one
SELECT count(*) FROM observation WHERE org_id = $1::uuid
`

type CountObservationsParams struct {
	OrgID pgtype.UUID
}

// CountObservations is the deduplication rate's denominator on a replayed set.
func (q *Queries) CountObservations(ctx context.Context, arg CountObservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countObservations, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO run (id, org_id, program_id, kind, scope, state, deadline, target_count)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::text, $5::text,
        'pending', $6::timestamptz, $7::int)
`

type CreateRunParams struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	ProgramID   pgtype.UUID
	Kind        string
	Scope       string
	Deadline    pgtype.Timestamptz
	TargetCount *int32
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.Exec(ctx, createRun,
		arg.ID,
		arg.OrgID,
		arg.ProgramID,
		arg.Kind,
		arg.Scope,
		arg.Deadline,
		arg.TargetCount,
	)
	return err
}

const ensurePartitions = `-- name: EnsurePartitions :one
SELECT ensure_monthly_partitions(to_regclass($1::text), $2::int)
`

type EnsurePartitionsParams struct {
	Target      string
	MonthsAhead int32
}

// EnsurePartitions creates this month's partition and the next ones.
func (q *Queries) EnsurePartitions(ctx context.Context, arg EnsurePartitionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, ensurePartitions, arg.Target, arg.MonthsAhead)
	var ensure_monthly_partitions int32
	err := row.Scan(&ensure_monthly_partitions)
	return ensure_monthly_partitions, err
}

const insertGenericPivot = `-- name: InsertGenericPivot :exec
INSERT INTO generic_pivot_value (pivot_type, pattern, note)
VALUES ($1::text, $2::text, $3::text)
ON CONFLICT (pivot_type, pattern) DO UPDATE SET note = EXCLUDED.note
`

type InsertGenericPivotParams struct {
	PivotType string
	Pattern   string
	Note      *string
}

func (q *Queries) InsertGenericPivot(ctx context.Context, arg InsertGenericPivotParams) error {
	_, err := q.db.Exec(ctx, insertGenericPivot, arg.PivotType, arg.Pattern, arg.Note)
	return err
}

const listProgramAssets = `-- name: ListProgramAssets :many
SELECT a.id, a.kind, a.key, a.host, a.scope_status, c.ip
  FROM asset a
  LEFT JOIN asset_current c ON c.asset_id = a.id
 WHERE a.program_id = $1::uuid
 ORDER BY a.id
`

type ListProgramAssetsParams struct {
	ProgramID pgtype.UUID
}

type ListProgramAssetsRow struct {
	ID          pgtype.UUID
	Kind        string
	Key         string
	Host        *string
	ScopeStatus string
	Ip          netip.Addr
}

// ListProgramAssets walks a program for a reclassification.
//
// The address comes with it. A CIDR rule can only match a name through what it
// resolved to, so a walk without one re-evaluates every asset a CIDR exclusion
// decided as though it had no address: it falls through to the apex include,
// becomes in scope again, and gets its due dates back. That is a scan outside
// the authorization, produced by the pass that exists to prevent one.
func (q *Queries) ListProgramAssets(ctx context.Context, arg ListProgramAssetsParams) ([]ListProgramAssetsRow, error) {
	rows, err := q.db.Query(ctx, listProgramAssets, arg.ProgramID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProgramAssetsRow{}
	for rows.Next() {
		var i ListProgramAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Key,
			&i.Host,
			&i.ScopeStatus,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunTargets = `-- name: ListRunTargets :many
SELECT key FROM run_target WHERE run_id = $1::uuid
`

type ListRunTargetsParams struct {
	RunID pgtype.UUID
}

func (q *Queries) ListRunTargets(ctx context.Context, arg ListRunTargetsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listRunTargets, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeRules = `-- name: ListScopeRules :many
SELECT id, kind, matcher, pattern
  FROM scope_rule
 WHERE program_id = $1::uuid
   AND valid_from <= $2::timestamptz
   AND (valid_to IS NULL OR valid_to > $2::timestamptz)
 ORDER BY id
`

type ListScopeRulesParams struct {
	ProgramID pgtype.UUID
	At        pgtype.Timestamptz
}

type ListScopeRulesRow struct {
	ID      pgtype.UUID
	Kind    string
	Matcher string
	Pattern string
}

// ListScopeRules returns a program's perimeter as it stands at an instant.
//
// The instant is a parameter rather than now(): valid_to is written by the
// application and now() is the database's clock, so comparing the two would
// make the answer depend on two clocks agreeing, and a rule closed a moment
// ago would read as still in force for the width of the gap.
func (q *Queries) ListScopeRules(ctx context.Context, arg ListScopeRulesParams) ([]ListScopeRulesRow, error) {
	rows, err := q.db.Query(ctx, listScopeRules, arg.ProgramID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScopeRulesRow{}
	for rows.Next() {
		var i ListScopeRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Matcher,
			&i.Pattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programForRun = `-- name: ProgramForRun :one
SELECT p.id, p.org_id, p.state, p.authorized_from, p.authorized_to
  FROM program p
 WHERE p.id = $1::uuid
`

type ProgramForRunParams struct {
	ProgramID pgtype.UUID
}

type ProgramForRunRow struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	State          string
	AuthorizedFrom pgtype.Timestamptz
	AuthorizedTo   pgtype.Timestamptz
}

// ProgramForRun reads what an ingestion has to check before writing anything.
//
// The authorization window is checked here rather than only the state: a run
// that started before an expiry must not write after it.
func (q *Queries) ProgramForRun(ctx context.Context, arg ProgramForRunParams) (ProgramForRunRow, error) {
	row := q.db.QueryRow(ctx, programForRun, arg.ProgramID)
	var i ProgramForRunRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
	)
	return i, err
}

const runForIngest = `-- name: RunForIngest :one
SELECT r.id, r.org_id, r.program_id, r.kind, r.scope, r.state, r.deadline,
       p.state AS program_state, p.authorized_from, p.authorized_to
  FROM run r
  JOIN program p ON p.id = r.program_id
 WHERE r.id = $1::uuid
`

type RunForIngestParams struct {
	RunID pgtype.UUID
}

type RunForIngestRow struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	ProgramID      pgtype.UUID
	Kind           string
	Scope          string
	State          string
	Deadline       pgtype.Timestamptz
	ProgramState   string
	AuthorizedFrom pgtype.Timestamptz
	AuthorizedTo   pgtype.Timestamptz
}

// RunForIngest reads everything an ingestion checks before writing anything.
//
// The authorization window comes back with the run rather than in a second
// query: a run that started before an expiry must not write after it, and the
// check is worth nothing if it is one somebody can forget to make.
func (q *Queries) RunForIngest(ctx context.Context, arg RunForIngestParams) (RunForIngestRow, error) {
	row := q.db.QueryRow(ctx, runForIngest, arg.RunID)
	var i RunForIngestRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.Kind,
		&i.Scope,
		&i.State,
		&i.Deadline,
		&i.ProgramState,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
	)
	return i, err
}

const upsertAssetAndProjection = `-- name: UpsertAssetAndProjection :one

WITH input AS (
    SELECT
        $1::uuid           AS id,
        $2::uuid             AS org_id,
        $3::uuid         AS program_id,
        $4::text               AS kind,
        $5::text                AS key,
        $6::text     AS host,
        $7::int      AS port,
        $8::text   AS scheme,
        $9::text   AS discovery_source,
        $10::jsonb  AS discovery_path,
        $11::uuid  AS parent_asset_id,
        $12::text       AS scope_status,
        $13::timestamptz     AS seen_at,
        $14::timestamptz AS next_resolve_at,
        $15::timestamptz    AS next_full_at,
        -- Derived in the control plane from the address the run connected to.
        -- They travel with the upsert rather than in a statement of their own:
        -- the enrichment is in hand at the moment the row is written, and a
        -- second round trip on the hottest write path is the thing the budget
        -- exists to refuse.
        $16::inet      AS ip,
        $17::int      AS asn,
        $18::text AS asn_org,
        $19::char(2) AS country,
        $20::text  AS region,
        $21::text    AS city
),
previous AS (
    SELECT a.id, a.scope_status, a.discovery_source, c.lifecycle
      FROM asset a
      LEFT JOIN asset_current c ON c.asset_id = a.id
      JOIN input i ON a.program_id = i.program_id AND a.kind = i.kind AND a.key = i.key
),
written AS (
    INSERT INTO asset (
        id, org_id, program_id, kind, key, host, parent_asset_id,
        discovery_source, discovery_path, scope_status, first_seen, last_seen)
    SELECT
        COALESCE((SELECT id FROM previous), i.id),
        i.org_id, i.program_id, i.kind, i.key, i.host, i.parent_asset_id,
        i.discovery_source, i.discovery_path, i.scope_status, i.seen_at, i.seen_at
      FROM input i
    ON CONFLICT (program_id, kind, key) DO UPDATE SET
        -- first_seen can only move backwards, which is what makes a cursor on
        -- it safe: a row that moves becomes older than a cursor already
        -- passed, so it is neither re-emitted nor missed.
        first_seen   = LEAST(asset.first_seen, EXCLUDED.first_seen),
        last_seen    = GREATEST(asset.last_seen, EXCLUDED.last_seen),
        -- Re-evaluated on every ingestion, not only when a run starts: that is
        -- what lets a rule change reclassify history without rescanning.
        scope_status = EXCLUDED.scope_status,
        -- Derivable from the key, so a row written before it was filled gets
        -- it on its next observation rather than through a catch-up migration
        -- that would reimplement key parsing in SQL.
        host         = COALESCE(asset.host, EXCLUDED.host),
        -- Never touched on conflict: its value is the one from the first
        -- appearance, which is exactly the question lineage asks.
        discovery_source = asset.discovery_source
    RETURNING id, (xmax = 0) AS created
),
projected AS (
    INSERT INTO asset_current (
        asset_id, org_id, program_id, kind, key, scope_status,
        host, port, scheme, next_resolve_at, next_full_at,
        ip, asn, asn_org, country, region, city, first_seen, last_seen)
    SELECT
        w.id, i.org_id, i.program_id, i.kind, i.key, i.scope_status,
        i.host, i.port, i.scheme,
        CASE WHEN i.scope_status = 'in_scope' THEN i.next_resolve_at END,
        CASE WHEN i.scope_status = 'in_scope' THEN i.next_full_at END,
        i.ip, i.asn, i.asn_org, i.country, i.region, i.city,
        i.seen_at, i.seen_at
      FROM written w, input i
    ON CONFLICT (asset_id) DO UPDATE SET
        first_seen   = LEAST(asset_current.first_seen, EXCLUDED.first_seen),
        last_seen    = GREATEST(asset_current.last_seen, EXCLUDED.last_seen),
        scope_status = EXCLUDED.scope_status,
        host         = COALESCE(asset_current.host, EXCLUDED.host),
        port         = COALESCE(asset_current.port, EXCLUDED.port),
        scheme       = COALESCE(asset_current.scheme, EXCLUDED.scheme),
        -- Re-evaluated on every pass rather than frozen: a target can move
        -- between two runs. COALESCE keeps what a pass without an address
        -- could not say, so an enrichment does not erase itself.
        ip      = COALESCE(EXCLUDED.ip, asset_current.ip),
        asn     = COALESCE(EXCLUDED.asn, asset_current.asn),
        asn_org = COALESCE(EXCLUDED.asn_org, asset_current.asn_org),
        country = COALESCE(EXCLUDED.country, asset_current.country),
        region  = COALESCE(EXCLUDED.region, asset_current.region),
        city    = COALESCE(EXCLUDED.city, asset_current.city),
        -- Only in-scope assets are scheduled. An asset leaving the perimeter
        -- loses its due dates in the same statement that reclassifies it,
        -- otherwise it keeps being scanned outside the authorization.
        next_resolve_at = CASE WHEN EXCLUDED.scope_status = 'in_scope'
                               THEN COALESCE(asset_current.next_resolve_at, EXCLUDED.next_resolve_at) END,
        next_full_at    = CASE WHEN EXCLUDED.scope_status = 'in_scope'
                               THEN COALESCE(asset_current.next_full_at, EXCLUDED.next_full_at) END,
        next_fingerprint_at = CASE WHEN EXCLUDED.scope_status = 'in_scope'
                                   THEN asset_current.next_fingerprint_at END
    RETURNING asset_id
)
SELECT
    w.id      AS asset_id,
    w.created AS created,
    p.scope_status     AS previous_scope_status,
    p.lifecycle        AS previous_lifecycle,
    p.discovery_source AS previous_discovery_source
  FROM written w
  LEFT JOIN previous p ON TRUE
 WHERE EXISTS (SELECT 1 FROM projected)
`

type UpsertAssetAndProjectionParams struct {
	AssetID         pgtype.UUID
	OrgID           pgtype.UUID
	ProgramID       pgtype.UUID
	Kind            string
	Key             string
	Host            *string
	Port            *int32
	Scheme          *string
	DiscoverySource string
	DiscoveryPath   []byte
	ParentAssetID   pgtype.UUID
	ScopeStatus     string
	SeenAt          pgtype.Timestamptz
	NextResolveAt   pgtype.Timestamptz
	NextFullAt      pgtype.Timestamptz
	Ip              netip.Addr
	Asn             *int32
	AsnOrg          *string
	Country         *string
	Region          *string
	City            *string
}

type UpsertAssetAndProjectionRow struct {
	AssetID                 pgtype.UUID
	Created                 bool
	PreviousScopeStatus     *string
	PreviousLifecycle       *string
	PreviousDiscoverySource *string
}

// Ingestion writes. The budget is a few round trips per observation, so what
// travels together travels in one statement rather than in a readable sequence
// of several.
// UpsertAssetAndProjection writes the identity and its projection at once, and
// returns the state that preceded them.
//
// The previous row is read on the snapshot the statement started from, so the
// CTE that inserts is invisible to the one that reads. That is what makes the
// previous lifecycle and the previous scope status free: the alternative is a
// second round trip on the hottest write path of the system.
//
// A left join rather than three scalar subqueries, so that the generator can
// see these are absent on a first appearance. A column it believes non-null is
// one the caller cannot scan the first time an asset is written.
func (q *Queries) UpsertAssetAndProjection(ctx context.Context, arg UpsertAssetAndProjectionParams) (UpsertAssetAndProjectionRow, error) {
	row := q.db.QueryRow(ctx, upsertAssetAndProjection,
		arg.AssetID,
		arg.OrgID,
		arg.ProgramID,
		arg.Kind,
		arg.Key,
		arg.Host,
		arg.Port,
		arg.Scheme,
		arg.DiscoverySource,
		arg.DiscoveryPath,
		arg.ParentAssetID,
		arg.ScopeStatus,
		arg.SeenAt,
		arg.NextResolveAt,
		arg.NextFullAt,
		arg.Ip,
		arg.Asn,
		arg.AsnOrg,
		arg.Country,
		arg.Region,
		arg.City,
	)
	var i UpsertAssetAndProjectionRow
	err := row.Scan(
		&i.AssetID,
		&i.Created,
		&i.PreviousScopeStatus,
		&i.PreviousLifecycle,
		&i.PreviousDiscoverySource,
	)
	return i, err
}

const writeObservation = `-- name: WriteObservation :one
WITH input AS (
    SELECT
        $1::uuid              AS org_id,
        $2::uuid            AS asset_id,
        $3::timestamptz  AS observed_at,
        $4::uuid    AS run_id,
        $5::text              AS source,
        $6::text               AS layer,
        $7::text             AS outcome,
        $8::text AS producer_version,
        $9::jsonb               AS data
),
head AS (
    SELECT o.id, o.observed_at, o.outcome, o.data, o.last_producer_version
      FROM observation o, input i
     WHERE o.asset_id = i.asset_id AND o.layer = i.layer
     ORDER BY o.observed_at DESC
     LIMIT 1
),
confirmed AS (
    UPDATE observation o SET
        -- Taken as a GREATEST rather than assigned: two probes landing at once
        -- could otherwise walk the confirmation window backwards and violate
        -- the constraint that keeps it ordered.
        last_confirmed_at = GREATEST(o.last_confirmed_at, i.observed_at),
        last_producer_version = COALESCE(i.producer_version, o.last_producer_version)
      FROM head h, input i
     WHERE o.id = h.id AND o.observed_at = h.observed_at
       AND h.outcome = i.outcome
       -- jsonb equality, which already ignores object key order. It does not
       -- ignore array element order, which is why normalization sorts the
       -- arrays whose order carries nothing.
       AND h.data = i.data
    RETURNING o.id
),
inserted AS (
    INSERT INTO observation (
        org_id, asset_id, observed_at, last_confirmed_at, run_id, source, layer,
        outcome, producer_version, last_producer_version, data)
    SELECT
        i.org_id, i.asset_id, i.observed_at, i.observed_at, i.run_id, i.source, i.layer,
        i.outcome, i.producer_version, i.producer_version, i.data
      FROM input i
     WHERE NOT EXISTS (SELECT 1 FROM confirmed)
    RETURNING id
)
SELECT
    EXISTS (SELECT 1 FROM confirmed) AS deduplicated,
    (SELECT h.data FROM head h WHERE NOT EXISTS (SELECT 1 FROM confirmed)) AS previous_data,
    (SELECT h.last_producer_version FROM head h WHERE NOT EXISTS (SELECT 1 FROM confirmed)) AS previous_producer_version
`

type WriteObservationParams struct {
	OrgID           pgtype.UUID
	AssetID         pgtype.UUID
	ObservedAt      pgtype.Timestamptz
	RunID           pgtype.UUID
	Source          string
	Layer           string
	Outcome         string
	ProducerVersion *string
	Data            []byte
}

type WriteObservationRow struct {
	Deduplicated            bool
	PreviousData            []byte
	PreviousProducerVersion *string
}

// WriteObservation deduplicates against the head of the chain.
//
// An observation is inserted only when it differs from the last one of the
// same (asset, layer). Each row then means "this state held from observed_at
// to last_confirmed_at", so volume drops by more than an order of magnitude
// without losing information, and two consecutive rows are two distinct states
// by construction.
//
// The comparison covers outcome and data and never the producer version. A
// version bump that changes nothing in the result must not write a row, which
// is the whole reason that version is stored twice.
//
// The previous payload comes back only when there was an insertion. Without
// that condition, every observation would drag its own payload across the wire
// while most of them deduplicate and have no diff to compute.
func (q *Queries) WriteObservation(ctx context.Context, arg WriteObservationParams) (WriteObservationRow, error) {
	row := q.db.QueryRow(ctx, writeObservation,
		arg.OrgID,
		arg.AssetID,
		arg.ObservedAt,
		arg.RunID,
		arg.Source,
		arg.Layer,
		arg.Outcome,
		arg.ProducerVersion,
		arg.Data,
	)
	var i WriteObservationRow
	err := row.Scan(&i.Deduplicated, &i.PreviousData, &i.PreviousProducerVersion)
	return i, err
}
