// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	CreatedBy pgtype.UUID
	Name      string
	TokenHash []byte
	Scopes    []string
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type AppUser struct {
	ID        pgtype.UUID
	Email     string
	CreatedAt pgtype.Timestamptz
}

type Asset struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	ProgramID       pgtype.UUID
	Kind            string
	Key             string
	Host            *string
	ParentAssetID   pgtype.UUID
	DiscoverySource string
	DiscoveryPath   []byte
	ScopeStatus     string
	FirstSeen       pgtype.Timestamptz
	LastSeen        pgtype.Timestamptz
}

type AssetCurrent struct {
	AssetID              pgtype.UUID
	OrgID                pgtype.UUID
	ProgramID            pgtype.UUID
	Kind                 string
	Key                  string
	ScopeStatus          string
	DnsState             *string
	TcpState             *string
	HttpState            *string
	Lifecycle            string
	NextResolveAt        pgtype.Timestamptz
	NextFullAt           pgtype.Timestamptz
	NextFingerprintAt    pgtype.Timestamptz
	FingerprintPriority  int16
	BackoffTier          int32
	TotalAttempts        int32
	HttpReachable        *bool
	FingerprintReachable *bool
	HttpStreak           int32
	FingerprintStreak    int32
	Host                 *string
	Port                 *int32
	Scheme               *string
	Ip                   netip.Addr
	StatusCode           *int32
	StatusChain          []int32
	FinalUrl             *string
	Title                *string
	Server               *string
	Asn                  *int32
	AsnOrg               *string
	Country              *string
	Region               *string
	City                 *string
	IsCdn                *bool
	CdnProvider          *string
	WafDetected          *bool
	WafVendor            *string
	Technologies         []string
	ChangeBuckets        []int32
	BucketsDay           pgtype.Date
	Attributes           []byte
	FirstSeen            pgtype.Timestamptz
	LastSeen             pgtype.Timestamptz
	LastCheckedAt        pgtype.Timestamptz
	LastFingerprintAt    pgtype.Timestamptz
	LastOkAt             pgtype.Timestamptz
	LastChangedAt        pgtype.Timestamptz
}

type AssetLayer struct {
	AssetID                pgtype.UUID
	OrgID                  pgtype.UUID
	Layer                  string
	State                  string
	InformativeFailures    int32
	NonInformativeFailures int32
	FirstFailureAt         pgtype.Timestamptz
	LastOkAt               pgtype.Timestamptz
	LastCheckedAt          pgtype.Timestamptz
}

type FaviconImage struct {
	OrgID     pgtype.UUID
	Hash      string
	MediaType string
	Bytes     []byte
	CreatedAt pgtype.Timestamptz
}

type GenericPivotValue struct {
	PivotType string
	Pattern   string
	Note      *string
}

type Membership struct {
	UserID pgtype.UUID
	OrgID  pgtype.UUID
	Role   string
}

type NotificationChannel struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Kind        string
	Url         string
	SecretRef   *string
	Template    *string
	Enabled     bool
	MinPriority string
	ManagedBy   string
	CreatedAt   pgtype.Timestamptz
}

type NotificationEvent struct {
	ID         int64
	OrgID      pgtype.UUID
	ProgramID  pgtype.UUID
	AssetID    pgtype.UUID
	Kind       string
	Priority   string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	NotifiedAt pgtype.Timestamptz
	Suppressed bool
}

type Observation struct {
	ID                  int64
	OrgID               pgtype.UUID
	AssetID             pgtype.UUID
	ObservedAt          pgtype.Timestamptz
	LastConfirmedAt     pgtype.Timestamptz
	RunID               pgtype.UUID
	Source              string
	Layer               string
	Outcome             string
	ProducerVersion     *string
	LastProducerVersion *string
	Data                []byte
}

type Org struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type PivotCount struct {
	OrgID      pgtype.UUID
	PivotType  string
	PivotValue string
	Count      int32
}

type Program struct {
	ID                pgtype.UUID
	OrgID             pgtype.UUID
	Name              string
	Platform          *string
	PlatformRef       *string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	AuthorizationRef  *string
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	State             string
	Version           int32
	CreatedBy         pgtype.UUID
	UpdatedBy         pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type Run struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	ProgramID   pgtype.UUID
	Kind        string
	Scope       string
	State       string
	Deadline    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	FinishedAt  pgtype.Timestamptz
	TargetCount *int32
	Summary     []byte
	Error       *string
	ExternalID  *string
}

type RunTarget struct {
	RunID   pgtype.UUID
	AssetID pgtype.UUID
	OrgID   pgtype.UUID
	Key     string
}

type ScopeRule struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Kind      string
	Matcher   string
	Pattern   string
	ValidFrom pgtype.Timestamptz
	ValidTo   pgtype.Timestamptz
	Note      *string
	Version   int32
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}
