// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notify.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const channelsForOrg = `-- name: ChannelsForOrg :many
SELECT id, url, secret_ref, template, min_priority, managed_by
  FROM notification_channel
 WHERE org_id = $1::uuid AND enabled
 ORDER BY created_at
`

type ChannelsForOrgParams struct {
	OrgID pgtype.UUID
}

type ChannelsForOrgRow struct {
	ID          pgtype.UUID
	Url         string
	SecretRef   *string
	Template    *string
	MinPriority string
	ManagedBy   string
}

// ChannelsForOrg is where an organization's alerts go.
func (q *Queries) ChannelsForOrg(ctx context.Context, arg ChannelsForOrgParams) ([]ChannelsForOrgRow, error) {
	rows, err := q.db.Query(ctx, channelsForOrg, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelsForOrgRow{}
	for rows.Next() {
		var i ChannelsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.SecretRef,
			&i.Template,
			&i.MinPriority,
			&i.ManagedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWindow = `-- name: CountWindow :one
SELECT count(*)
  FROM notification_event
 WHERE program_id = $1::uuid
   AND priority = $2::text
   AND asset_id IS NOT NULL
   AND notified_at >= $3::timestamptz
`

type CountWindowParams struct {
	ProgramID pgtype.UUID
	Priority  string
	Since     pgtype.Timestamptz
}

// CountWindow is how many of a programme's events at one priority were sent
// inside the window.
//
// Read from the table rather than from state the notifier holds in memory. An
// in-memory counter resets on restart, which reopens the tap exactly when one
// restarts because of an incident.
//
// An event with no asset does not consume the window either: counting it would
// shrink the cap at the precise moment a programme went dark, which is when the
// most room is needed.
func (q *Queries) CountWindow(ctx context.Context, arg CountWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWindow, arg.ProgramID, arg.Priority, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const digestInWindow = `-- name: DigestInWindow :one
SELECT count(*) FROM notification_event
 WHERE program_id = $1::uuid
   AND kind = 'digest'
   AND priority = $2::text
   AND created_at >= $3::timestamptz
`

type DigestInWindowParams struct {
	ProgramID pgtype.UUID
	Priority  string
	Since     pgtype.Timestamptz
}

// DigestInWindow reports whether a summary already speaks for this window.
//
// Without it every suppressed event past the cap writes its own summary, and an
// anti-flood that produces one notification per suppressed notification is not
// one.
func (q *Queries) DigestInWindow(ctx context.Context, arg DigestInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, digestInWindow, arg.ProgramID, arg.Priority, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markNotified = `-- name: MarkNotified :exec
UPDATE notification_event SET notified_at = $1::timestamptz
 WHERE id = $2::bigint AND created_at = $3::timestamptz
`

type MarkNotifiedParams struct {
	At        pgtype.Timestamptz
	ID        int64
	CreatedAt pgtype.Timestamptz
}

// MarkNotified closes one event.
//
// By (id, created_at) rather than id alone: the primary key is composite, and
// forgetting the second half scans every partition on each mark.
func (q *Queries) MarkNotified(ctx context.Context, arg MarkNotifiedParams) error {
	_, err := q.db.Exec(ctx, markNotified, arg.At, arg.ID, arg.CreatedAt)
	return err
}

const onboardingDue = `-- name: OnboardingDue :many
WITH held AS (
    SELECT e.org_id, e.program_id, count(*) AS held
      FROM notification_event e
     WHERE e.suppressed
       AND e.kind = 'new_active'
       -- A window overflow writes a digest too, and any digest excluding a
       -- programme here would silence its onboarding summary for good: a large
       -- first run saturates the high window on port openings, which the grace
       -- does not hold, so the overflow digest would land first and the
       -- onboarding one never.
       AND NOT EXISTS (
             SELECT 1 FROM notification_event d
              WHERE d.program_id = e.program_id
                AND d.kind = 'digest'
                AND d.payload ->> 'reason' = 'first run')
       -- The grace is at most seven days, so nothing older can still be
       -- waiting for one. Without the bound this walks every suppressed row of
       -- the retention window, twice a minute, forever.
       AND e.created_at > $1::timestamptz
     GROUP BY e.org_id, e.program_id
)
SELECT h.org_id, h.program_id, p.name, p.created_at, h.held,
       EXISTS (SELECT 1 FROM run r
                WHERE r.program_id = p.id AND r.kind = 'discovery'
                  AND r.state = 'completed') AS completed_discovery,
       EXISTS (SELECT 1 FROM run r
                WHERE r.program_id = p.id AND r.kind = 'discovery') AS any_discovery,
       (SELECT count(*) FROM asset a WHERE a.program_id = p.id) AS assets
  FROM held h
  JOIN program p ON p.id = h.program_id
 ORDER BY h.program_id
`

type OnboardingDueParams struct {
	Since pgtype.Timestamptz
}

type OnboardingDueRow struct {
	OrgID              pgtype.UUID
	ProgramID          pgtype.UUID
	Name               string
	CreatedAt          pgtype.Timestamptz
	Held               int64
	CompletedDiscovery bool
	AnyDiscovery       bool
	Assets             int64
}

// OnboardingDue finds the programmes whose first run is over and whose flood
// has never been summarised.
//
// The summary is emitted when the grace ends, not during. Summarising while the
// run is going would produce one summary per batch, each carrying a count
// already wrong by the time it is written.
//
// And it is emitted at all, which is the point: an overflow must never produce
// the absence of a notification. That is how an anti-flood turns into a loss of
// signal, and a first run that says nothing at all is the same failure wearing
// a different name.
func (q *Queries) OnboardingDue(ctx context.Context, arg OnboardingDueParams) ([]OnboardingDueRow, error) {
	rows, err := q.db.Query(ctx, onboardingDue, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnboardingDueRow{}
	for rows.Next() {
		var i OnboardingDueRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ProgramID,
			&i.Name,
			&i.CreatedAt,
			&i.Held,
			&i.CompletedDiscovery,
			&i.AnyDiscovery,
			&i.Assets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oneOrganization = `-- name: OneOrganization :many
SELECT id FROM org ORDER BY created_at LIMIT 2
`

// OneOrganization is the condition the configured channel is bootstrapped
// under.
//
// A configuration file has no way to name a tenant, so exactly one organization
// is the only case where the intent is unambiguous. Beyond it, giving a global
// URL to one of several organizations would leak one tenant's alerts into
// another's channel.
func (q *Queries) OneOrganization(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, oneOrganization)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingEvents = `-- name: PendingEvents :many
SELECT e.id, e.created_at, e.org_id, e.program_id, e.asset_id, e.kind, e.priority, e.payload,
       a.key AS asset_key, p.name AS program_name
  FROM notification_event e
  JOIN program p ON p.id = e.program_id
  LEFT JOIN asset a ON a.id = e.asset_id
 WHERE e.notified_at IS NULL
   AND NOT e.suppressed
 ORDER BY CASE e.priority
              WHEN 'critical' THEN 0 WHEN 'high' THEN 1
              WHEN 'medium' THEN 2 ELSE 3 END,
          e.created_at
 LIMIT $1::int
`

type PendingEventsParams struct {
	Batch int32
}

type PendingEventsRow struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	OrgID       pgtype.UUID
	ProgramID   pgtype.UUID
	AssetID     pgtype.UUID
	Kind        string
	Priority    string
	Payload     []byte
	AssetKey    *string
	ProgramName string
}

// PendingEvents is the notifier's queue.
//
// Ordered by priority so a takeover leaves before a title change, and the
// partial index means a closed month costs an empty index to consult rather
// than a month of rows to filter.
func (q *Queries) PendingEvents(ctx context.Context, arg PendingEventsParams) ([]PendingEventsRow, error) {
	rows, err := q.db.Query(ctx, pendingEvents, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PendingEventsRow{}
	for rows.Next() {
		var i PendingEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.OrgID,
			&i.ProgramID,
			&i.AssetID,
			&i.Kind,
			&i.Priority,
			&i.Payload,
			&i.AssetKey,
			&i.ProgramName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeSuppressed = `-- name: PurgeSuppressed :execrows
DELETE FROM notification_event
 WHERE suppressed AND created_at < $1::timestamptz
`

type PurgeSuppressedParams struct {
	Before pgtype.Timestamptz
}

// PurgeSuppressed drops the onboarding and overflow noise.
//
// A targeted DELETE inside the partitions rather than a partition drop: those
// rows are written in waves and the delete is bounded. Partitioning on
// suppressed would be the wrong axis.
func (q *Queries) PurgeSuppressed(ctx context.Context, arg PurgeSuppressedParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeSuppressed, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stuckEvents = `-- name: StuckEvents :one
SELECT count(*) FROM notification_event
 WHERE notified_at IS NULL AND NOT suppressed AND created_at < $1::timestamptz
`

type StuckEventsParams struct {
	Before pgtype.Timestamptz
}

// StuckEvents counts what has been neither notified nor suppressed for too
// long.
//
// A broken notifier is a silent failure by nature: nothing else announces it,
// ingestion keeps writing and the inventory stays correct. It is the kind of
// outage that goes unnoticed until the takeover it misses.
func (q *Queries) StuckEvents(ctx context.Context, arg StuckEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, stuckEvents, arg.Before)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const suppressWindow = `-- name: SuppressWindow :execrows
UPDATE notification_event SET suppressed = true
 WHERE id = ANY($1::bigint[]) AND created_at = ANY($2::timestamptz[])
`

type SuppressWindowParams struct {
	Ids        []int64
	CreatedAts []pgtype.Timestamptz
}

// SuppressWindow marks what the summary speaks for.
//
// The individual events stay in the database, readable and not sent. An
// overflow must never produce the absence of a notification, which is how an
// anti-flood turns into a loss of signal.
func (q *Queries) SuppressWindow(ctx context.Context, arg SuppressWindowParams) (int64, error) {
	result, err := q.db.Exec(ctx, suppressWindow, arg.Ids, arg.CreatedAts)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const suppressedInWindow = `-- name: SuppressedInWindow :one
SELECT count(*) FROM notification_event
 WHERE program_id = $1::uuid
   AND priority = $2::text
   AND suppressed
   AND created_at >= $3::timestamptz
`

type SuppressedInWindowParams struct {
	ProgramID pgtype.UUID
	Priority  string
	Since     pgtype.Timestamptz
}

// SuppressedInWindow is what the summary stands for.
func (q *Queries) SuppressedInWindow(ctx context.Context, arg SuppressedInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, suppressedInWindow, arg.ProgramID, arg.Priority, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertConfigChannel = `-- name: UpsertConfigChannel :exec
INSERT INTO notification_channel (id, org_id, url, template, min_priority, managed_by)
VALUES ($1::uuid, $2::uuid, $3::text, $4::text,
        $5::text, 'config')
ON CONFLICT (org_id) WHERE managed_by = 'config' DO UPDATE SET
    url          = EXCLUDED.url,
    template     = EXCLUDED.template,
    min_priority = EXCLUDED.min_priority,
    enabled      = true
`

type UpsertConfigChannelParams struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Url         string
	Template    *string
	MinPriority string
}

// UpsertConfigChannel is the bootstrap of the configured output.
//
// Keyed on the organization and the config marker rather than on the URL.
// Without that, changing the configured URL and restarting inserts a second
// active row without disabling the first, and every alert goes out twice, one
// of them to the destination just replaced.
func (q *Queries) UpsertConfigChannel(ctx context.Context, arg UpsertConfigChannelParams) error {
	_, err := q.db.Exec(ctx, upsertConfigChannel,
		arg.ID,
		arg.OrgID,
		arg.Url,
		arg.Template,
		arg.MinPriority,
	)
	return err
}

type WriteEventsParams struct {
	OrgID      pgtype.UUID
	ProgramID  pgtype.UUID
	AssetID    pgtype.UUID
	Kind       string
	Priority   string
	Payload    []byte
	CreatedAt  pgtype.Timestamptz
	Suppressed bool
}
