// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRunTargets = `-- name: AddRunTargets :execrows
INSERT INTO run_target (run_id, asset_id, org_id, key)
SELECT $1::uuid, ($2::uuid[])[i], $3::uuid, ($4::text[])[i]
  FROM generate_subscripts($2::uuid[], 1) AS i
`

type AddRunTargetsParams struct {
	RunID    pgtype.UUID
	AssetIds []pgtype.UUID
	OrgID    pgtype.UUID
	Keys     []string
}

// AddRunTargets freezes the list in one round trip.
//
// One statement rather than one per target: a batch is hundreds of rows, and a
// run that costs five hundred round trips to define is one nobody will let the
// scheduler start often.
//
// Columns as parallel arrays rather than COPY, and not by preference.
// PostgreSQL refuses COPY FROM outright on a table carrying a policy, with
// "COPY FROM not supported with row-level security", so the copy path stopped
// working the day isolation was enabled. This is the same single round trip,
// and it makes the organization a scalar of the statement rather than a column
// repeated per row, so a batch mixing two tenants is no longer expressible.
//
// generate_subscripts rather than a multi-argument unnest, which sqlc's
// analyser cannot type. The arrays are built together by the caller and are the
// same length by construction; a short one would read as nulls rather than
// fail, which is why they are built in one loop and never assembled.
//
// @tenant: scoped
func (q *Queries) AddRunTargets(ctx context.Context, arg AddRunTargetsParams) (int64, error) {
	result, err := q.db.Exec(ctx, addRunTargets,
		arg.RunID,
		arg.AssetIds,
		arg.OrgID,
		arg.Keys,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const apexesForProgram = `-- name: ApexesForProgram :many
SELECT DISTINCT pattern
  FROM scope_rule
 WHERE program_id = $1::uuid
   AND kind = 'include'
   AND matcher = 'apex'
   AND valid_from <= $2::timestamptz
   AND (valid_to IS NULL OR valid_to > $2::timestamptz)
 ORDER BY pattern
`

type ApexesForProgramParams struct {
	ProgramID pgtype.UUID
	At        pgtype.Timestamptz
}

// ApexesForProgram is a discovery run's perimeter.
//
// @tenant: keyed
func (q *Queries) ApexesForProgram(ctx context.Context, arg ApexesForProgramParams) ([]string, error) {
	rows, err := q.db.Query(ctx, apexesForProgram, arg.ProgramID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		items = append(items, pattern)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exclusionsForProgram = `-- name: ExclusionsForProgram :many
SELECT DISTINCT matcher, pattern
  FROM scope_rule
 WHERE program_id = $1::uuid
   AND kind = 'exclude'
   AND valid_from <= $2::timestamptz
   AND (valid_to IS NULL OR valid_to > $2::timestamptz)
 ORDER BY matcher, pattern
`

type ExclusionsForProgramParams struct {
	ProgramID pgtype.UUID
	At        pgtype.Timestamptz
}

type ExclusionsForProgramRow struct {
	Matcher string
	Pattern string
}

// ExclusionsForProgram is the second safety net in front of the network.
//
// The patterns travel with the perimeter rather than being trusted to the
// scope re-evaluation at ingestion, because a rule may have changed between a
// run being defined and a run starting, and the re-evaluation happens after the
// packet. One probe too many is not much, and it is not a property to accept
// knowingly when the pattern fits in the invocation.
//
// @tenant: keyed
func (q *Queries) ExclusionsForProgram(ctx context.Context, arg ExclusionsForProgramParams) ([]ExclusionsForProgramRow, error) {
	rows, err := q.db.Query(ctx, exclusionsForProgram, arg.ProgramID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExclusionsForProgramRow{}
	for rows.Next() {
		var i ExclusionsForProgramRow
		if err := rows.Scan(&i.Matcher, &i.Pattern); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireRuns = `-- name: ExpireRuns :many
UPDATE run SET
    state       = 'expired',
    finished_at = $1::timestamptz,
    error       = COALESCE(error, 'the deadline passed and no report was delivered')
 WHERE state IN ('pending', 'running')
   AND deadline <= $1::timestamptz
RETURNING id, org_id, program_id, kind, scope, started_at, target_count
`

type ExpireRunsParams struct {
	At pgtype.Timestamptz
}

type ExpireRunsRow struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	ProgramID   pgtype.UUID
	Kind        string
	Scope       string
	StartedAt   pgtype.Timestamptz
	TargetCount *int32
}

// ExpireRuns is the deadline sweeper.
//
// It does not have to repair anything. Due dates are moved only when a report
// is ingested, so an abandoned run leaves the inventory exactly as it found it;
// expiring it frees its targets and makes the failure visible.
//
// @tenant: cross-org
// @why: the deadline sweeper serves every tenant in one tick. A run nothing
//
//	expires holds its targets forever, and the assets it froze are invisible to
//	every later pass.
func (q *Queries) ExpireRuns(ctx context.Context, arg ExpireRunsParams) ([]ExpireRunsRow, error) {
	rows, err := q.db.Query(ctx, expireRuns, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireRunsRow{}
	for rows.Next() {
		var i ExpireRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProgramID,
			&i.Kind,
			&i.Scope,
			&i.StartedAt,
			&i.TargetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveRunForProgram = `-- name: LiveRunForProgram :one
SELECT id, kind, scope, state, deadline, created_at, started_at, target_count
  FROM run
 WHERE program_id = $1::uuid
   AND kind = $2::text
   AND state IN ('pending', 'running')
 ORDER BY created_at DESC
 LIMIT 1
`

type LiveRunForProgramParams struct {
	ProgramID pgtype.UUID
	Kind      string
}

type LiveRunForProgramRow struct {
	ID          pgtype.UUID
	Kind        string
	Scope       string
	State       string
	Deadline    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	TargetCount *int32
}

// LiveRunForProgram is what a second request runs into.
//
// started_at comes back with it because it is the only thing that separates a
// run something has actually opened from one whose provisioning failed, and
// those two call for opposite actions.
//
// @tenant: keyed
func (q *Queries) LiveRunForProgram(ctx context.Context, arg LiveRunForProgramParams) (LiveRunForProgramRow, error) {
	row := q.db.QueryRow(ctx, liveRunForProgram, arg.ProgramID, arg.Kind)
	var i LiveRunForProgramRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Scope,
		&i.State,
		&i.Deadline,
		&i.CreatedAt,
		&i.StartedAt,
		&i.TargetCount,
	)
	return i, err
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE run SET
    state      = 'running',
    started_at = COALESCE(started_at, $1::timestamptz)
 WHERE id = $2::uuid AND state = 'pending'
`

type MarkRunRunningParams struct {
	At    pgtype.Timestamptz
	RunID pgtype.UUID
}

// MarkRunRunning records that a scanner opened the run.
//
// @tenant: keyed
func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) error {
	_, err := q.db.Exec(ctx, markRunRunning, arg.At, arg.RunID)
	return err
}

const programForScheduling = `-- name: ProgramForScheduling :one
SELECT id, org_id, name, state, authorized_from, authorized_to, rate_limit_rps,
       discovery_interval, last_discovery_at, version
  FROM program
 WHERE id = $1::uuid
`

type ProgramForSchedulingParams struct {
	ProgramID pgtype.UUID
}

type ProgramForSchedulingRow struct {
	ID                pgtype.UUID
	OrgID             pgtype.UUID
	Name              string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
}

// ProgramForScheduling reads what a run needs to be defined.
//
// @tenant: keyed
func (q *Queries) ProgramForScheduling(ctx context.Context, arg ProgramForSchedulingParams) (ProgramForSchedulingRow, error) {
	row := q.db.QueryRow(ctx, programForScheduling, arg.ProgramID)
	var i ProgramForSchedulingRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
		&i.RateLimitRps,
		&i.DiscoveryInterval,
		&i.LastDiscoveryAt,
		&i.Version,
	)
	return i, err
}

const programsDueForCandidates = `-- name: ProgramsDueForCandidates :many
SELECT p.id, p.org_id, p.name
  FROM program p
  JOIN asset_current c ON c.program_id = p.id
 WHERE p.state = 'active'
   AND p.authorized_from <= $1::timestamptz
   AND (p.authorized_to IS NULL OR p.authorized_to > $1::timestamptz)
   AND c.kind = 'fqdn'
   AND c.scope_status = 'in_scope'
   AND c.lifecycle = 'candidate'
   AND c.next_full_at IS NULL
   AND c.next_resolve_at <= $1::timestamptz
   AND NOT EXISTS (
        SELECT 1 FROM run r
         WHERE r.program_id = p.id
           AND r.kind = 'candidate'
           AND r.state IN ('pending', 'running'))
 GROUP BY p.id, p.org_id, p.name
 ORDER BY p.id
`

type ProgramsDueForCandidatesParams struct {
	At pgtype.Timestamptz
}

type ProgramsDueForCandidatesRow struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
	Name  string
}

// ProgramsDueForCandidates wakes the lane that must not wait.
//
// The difference from ProgramsDueForVerification is the whole reason the lane
// exists, and it is one line: only a live *candidate* run holds this pass back.
//
// A live verification does not, which is the point: a sweep holds its slot for
// its whole deadline, and a candidate arriving a minute in would wait half an
// hour for a check the aggressive curve wanted at sixty seconds.
//
// Nor does a live discovery, and that is a decision rather than an oversight.
// Discovery blocks verification because a full sweep would send a second
// scanner at hosts the first one is connected to. A resolve sends nothing to
// the target at all, so there is nothing to collide with, and blocking here
// would spend the freshness advantage on a run that cannot interfere with it.
//
// @tenant: cross-org
// @why: the candidate pass provisions for every programme of every tenant in
//
//	one pass, exactly as the due date pass does.
func (q *Queries) ProgramsDueForCandidates(ctx context.Context, arg ProgramsDueForCandidatesParams) ([]ProgramsDueForCandidatesRow, error) {
	rows, err := q.db.Query(ctx, programsDueForCandidates, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramsDueForCandidatesRow{}
	for rows.Next() {
		var i ProgramsDueForCandidatesRow
		if err := rows.Scan(&i.ID, &i.OrgID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programsDueForDiscovery = `-- name: ProgramsDueForDiscovery :many
SELECT p.id, p.org_id, p.name, p.rate_limit_rps
  FROM program p
 WHERE p.state = 'active'
   AND p.authorized_from <= $1::timestamptz
   AND (p.authorized_to IS NULL OR p.authorized_to > $1::timestamptz)
   AND (p.last_discovery_at IS NULL
        OR p.last_discovery_at + p.discovery_interval <= $1::timestamptz
        -- Or the last discovery ended without delivering, and the retry delay
        -- has passed. A run that failed in thirty seconds must not cost a week
        -- of coverage, and clearing last_discovery_at instead would be worse
        -- twice over: it destroys the record of when this programme was last
        -- enumerated, and it turns a permanently broken runner into a loop that
        -- provisions on every tick and bills every one of them.
        OR EXISTS (
             SELECT 1 FROM run r
              WHERE r.program_id = p.id
                AND r.kind = 'discovery'
                AND r.state IN ('expired', 'failed')
                AND r.finished_at + $2::interval <= $1::timestamptz
                AND NOT EXISTS (
                      SELECT 1 FROM run later
                       WHERE later.program_id = p.id
                         AND later.kind = 'discovery'
                         AND later.created_at > r.created_at)))
   -- The condition that does the work. It prevents a provisioning storm and
   -- bounds concurrency to one discovery run per programme.
   AND NOT EXISTS (
        SELECT 1 FROM run r
         WHERE r.program_id = p.id AND r.kind = 'discovery'
           AND r.state IN ('pending', 'running'))
   -- A programme with nothing to enumerate is not due. It would otherwise be
   -- selected on every tick and refused on every tick, which at a one minute
   -- cadence is a warning a minute forever rather than a signal.
   AND EXISTS (
        SELECT 1 FROM scope_rule s
         WHERE s.program_id = p.id
           AND s.kind = 'include' AND s.matcher = 'apex'
           AND s.valid_from <= $1::timestamptz
           AND (s.valid_to IS NULL OR s.valid_to > $1::timestamptz))
 ORDER BY p.id
`

type ProgramsDueForDiscoveryParams struct {
	At    pgtype.Timestamptz
	Retry pgtype.Interval
}

type ProgramsDueForDiscoveryRow struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	Name         string
	RateLimitRps int32
}

// ProgramsDueForDiscovery is the pass that provisions enumeration.
//
// The authorization window is checked here rather than only the state. Without
// those two lines an expired programme would be provisioned on every tick and
// refused when the run opens: an execution billed to do nothing, every thirty
// seconds.
//
// @tenant: cross-org
// @why: the discovery cadence provisions enumeration for every programme of
//
//	every tenant in one pass, and a per tenant sweep would need a list of tenants
//	to walk, which is the same crossing wearing a loop.
func (q *Queries) ProgramsDueForDiscovery(ctx context.Context, arg ProgramsDueForDiscoveryParams) ([]ProgramsDueForDiscoveryRow, error) {
	rows, err := q.db.Query(ctx, programsDueForDiscovery, arg.At, arg.Retry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramsDueForDiscoveryRow{}
	for rows.Next() {
		var i ProgramsDueForDiscoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.RateLimitRps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const programsDueForVerification = `-- name: ProgramsDueForVerification :many
SELECT p.id, p.org_id, p.name,
       bool_or(c.next_full_at <= $1::timestamptz) AS full_due
  FROM program p
  JOIN asset_current c ON c.program_id = p.id
 WHERE p.state = 'active'
   AND p.authorized_from <= $1::timestamptz
   AND (p.authorized_to IS NULL OR p.authorized_to > $1::timestamptz)
   -- The same predicate the selection uses, so a programme is never woken for
   -- work the selection would then refuse to find. A name is the unit: an
   -- address is never a target of its own, and a service is observed through
   -- its host's run.
   AND c.kind = 'fqdn'
   AND c.scope_status = 'in_scope'
   AND c.lifecycle <> 'archived'
   AND NOT (c.lifecycle = 'candidate' AND c.next_full_at IS NULL)
   AND (c.next_full_at <= $1::timestamptz OR c.next_resolve_at <= $1::timestamptz)
   AND NOT EXISTS (
        SELECT 1 FROM run r
         WHERE r.program_id = p.id
           -- Either kind. A live verification is the bound the unique index
           -- keeps; a live discovery is the perimeter being walked right now,
           -- and it freezes no targets because it is the one allowed to find
           -- things, so nothing else can see the hosts it is scanning. Waking a
           -- programme in that state would select assets whose report has not
           -- landed yet, and send a second scanner at hosts the first one is
           -- connected to.
           AND r.kind IN ('verification', 'discovery')
           AND r.state IN ('pending', 'running'))
 GROUP BY p.id, p.org_id, p.name
 ORDER BY p.id
`

type ProgramsDueForVerificationParams struct {
	At pgtype.Timestamptz
}

type ProgramsDueForVerificationRow struct {
	ID      pgtype.UUID
	OrgID   pgtype.UUID
	Name    string
	FullDue bool
}

// ProgramsDueForVerification is the pass on due dates.
//
// The counterpart of the discovery cadence and the thing that was missing: due
// dates were written, the queue view counted them as what the next tick can
// dispatch, and no tick dispatched them. The engine has existed since
// verification was built; only the trigger was absent, so a run went out when
// somebody pressed a button and never otherwise.
//
// The authorization window is checked here as well as at the run, and what it
// buys is worth stating exactly rather than borrowing the discovery pass's
// sentence. Nothing is billed either way: the run is refused before the platform
// is called. What this prevents is the pass waking an expired programme, walking
// its due assets, freezing nothing and logging a refusal, once a minute, forever
// until somebody edits the programme. A warning a minute is not a signal.
//
// full_due decides the rung without a second query. A full run executes every
// rung below it and moves both dates, so taking full first cannot starve
// resolve, and an asset due for full does not need a resolve run.
//
// The absence of a live verification run is the condition that does the work,
// exactly as it is for discovery. It is not the guarantee: that is the unique
// index, because a check that reads and then writes is not a reservation under
// read committed. This only keeps the pass from provisioning what the index
// would refuse, once a minute, forever.
//
// @tenant: cross-org
// @why: the due date pass provisions verification for every programme of every
//
//	tenant in one pass, and a per tenant sweep would need a list of tenants to
//	walk, which is the same crossing wearing a loop.
func (q *Queries) ProgramsDueForVerification(ctx context.Context, arg ProgramsDueForVerificationParams) ([]ProgramsDueForVerificationRow, error) {
	rows, err := q.db.Query(ctx, programsDueForVerification, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramsDueForVerificationRow{}
	for rows.Next() {
		var i ProgramsDueForVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.FullDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRunStart = `-- name: RecordRunStart :exec
UPDATE run SET external_id = $1::text WHERE id = $2::uuid
`

type RecordRunStartParams struct {
	ExternalID string
	RunID      pgtype.UUID
}

// RecordRunStart names the execution the platform created.
//
// Written after the start rather than with the run, because the run is
// committed first: a platform that refuses on a quota must leave a row the
// deadline sweeper owns, not an absence.
//
// @tenant: keyed
func (q *Queries) RecordRunStart(ctx context.Context, arg RecordRunStartParams) error {
	_, err := q.db.Exec(ctx, recordRunStart, arg.ExternalID, arg.RunID)
	return err
}

const runForTargets = `-- name: RunForTargets :one
SELECT r.id, r.org_id, r.program_id, r.kind, r.scope, r.state, r.deadline
  FROM run r
 WHERE r.id = $1::uuid
`

type RunForTargetsParams struct {
	RunID pgtype.UUID
}

type RunForTargetsRow struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Kind      string
	Scope     string
	State     string
	Deadline  pgtype.Timestamptz
}

// RunForTargets reads what the target list endpoint has to check.
//
// @tenant: keyed
func (q *Queries) RunForTargets(ctx context.Context, arg RunForTargetsParams) (RunForTargetsRow, error) {
	row := q.db.QueryRow(ctx, runForTargets, arg.RunID)
	var i RunForTargetsRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.Kind,
		&i.Scope,
		&i.State,
		&i.Deadline,
	)
	return i, err
}

const selectDueCandidates = `-- name: SelectDueCandidates :many
SELECT c.asset_id, c.key, c.lifecycle, c.backoff_tier
  FROM asset_current c
 WHERE c.org_id = $1::uuid
   AND c.program_id = $2::uuid
   AND c.kind = 'fqdn'
   AND c.scope_status = 'in_scope'
   AND c.lifecycle = 'candidate'
   -- The pair, not the lifecycle. A hand entered host is a candidate too until
   -- it answers, and it carries a full date because somebody typed it in to
   -- find out what it exposes: taking it here would answer that a name
   -- resolves and never sweep a port.
   AND c.next_full_at IS NULL
   AND c.next_resolve_at <= $3::timestamptz
   -- The lease is the same one, across lanes as well as within one: a host
   -- frozen by a verification run is not taken by a candidate run either.
   AND NOT EXISTS (
        SELECT 1 FROM run_target t
          JOIN run r ON r.id = t.run_id
         WHERE t.asset_id = c.asset_id
           AND r.state IN ('pending', 'running'))
 ORDER BY c.next_resolve_at, c.asset_id
 LIMIT $4::int
`

type SelectDueCandidatesParams struct {
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	At        pgtype.Timestamptz
	Batch     int32
}

type SelectDueCandidatesRow struct {
	AssetID     pgtype.UUID
	Key         string
	Lifecycle   string
	BackoffTier int32
}

// SelectDueCandidates is the candidate lane's half of the selection.
//
// The same columns and the same lease as SelectDueHosts, with the lifecycle
// reversed: a candidate is selected by this and by no other pass, or the two
// fight over the same names and each freezes what the other was about to take.
//
// The rung is not a parameter. A candidate run is pinned to resolve by a CHECK
// on the table, because one round trip to a resolver pool and nothing sent to
// the target is what lets this lane run beside a verification without adding up
// to anything the rate budget has an opinion about.
//
// @tenant: scoped
func (q *Queries) SelectDueCandidates(ctx context.Context, arg SelectDueCandidatesParams) ([]SelectDueCandidatesRow, error) {
	rows, err := q.db.Query(ctx, selectDueCandidates,
		arg.OrgID,
		arg.ProgramID,
		arg.At,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDueCandidatesRow{}
	for rows.Next() {
		var i SelectDueCandidatesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Key,
			&i.Lifecycle,
			&i.BackoffTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueHosts = `-- name: SelectDueHosts :many

SELECT c.asset_id, c.key, c.lifecycle, c.backoff_tier
  FROM asset_current c
 WHERE c.org_id = $1::uuid
   AND c.program_id = $2::uuid
   AND c.kind = 'fqdn'
   AND c.scope_status = 'in_scope'
   AND c.lifecycle <> 'archived'
   -- What belongs to the candidate lane, excluded here because the exclusion is
   -- mutual: without it the two passes fight over the same names, each freezing
   -- what the other was about to take, and which one wins is whichever tick
   -- fired first.
   --
   -- The lane is the pair and never the lifecycle alone, and that correction is
   -- worth the two lines it costs. CANDIDATE is not a Certificate Transparency
   -- state: a host somebody typed into the assets form is one too, until its
   -- first answer. Excluding on the lifecycle alone would divert it into a lane
   -- pinned to resolve, where a resolution would report that the name answers
   -- and nothing would ever sweep its ports, which is the opposite of what a
   -- hand entered host is promised and it is promised it because a person is
   -- waiting.
   --
   -- A null full date is what actually separates them. A candidate that has not
   -- earned the expensive rung is exactly the state the aggressive curve
   -- describes, and it is readable here without joining the asset's source.
   AND NOT (c.lifecycle = 'candidate' AND c.next_full_at IS NULL)
   AND CASE WHEN $3::text = 'full' THEN c.next_full_at ELSE c.next_resolve_at END
       <= $4::timestamptz
   -- The lease, and the whole of it. Two runs never hold the same host, and a
   -- run that dies frees its hosts by expiring rather than by restitution.
   AND NOT EXISTS (
        SELECT 1 FROM run_target t
          JOIN run r ON r.id = t.run_id
         WHERE t.asset_id = c.asset_id
           AND r.state IN ('pending', 'running'))
 ORDER BY CASE WHEN $3::text = 'full' THEN c.next_full_at ELSE c.next_resolve_at END,
          c.asset_id
 LIMIT $5::int
`

type SelectDueHostsParams struct {
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Rung      string
	At        pgtype.Timestamptz
	Batch     int32
}

type SelectDueHostsRow struct {
	AssetID     pgtype.UUID
	Key         string
	Lifecycle   string
	BackoffTier int32
}

// Runs: selecting what is due, freezing it, and expiring what never delivered.
//
// There is no queue table and no lease column. Three due dates decide
// eligibility, and the frozen target list of a run is the whole of the
// reservation: selection skips what a live run already holds, and the
// reservation expires when the run does.
// SelectDueHosts is the scheduler's pass.
//
// The tiebreaker on the identity is not decoration. Assets are written in bulk,
// so thousands of rows routinely carry the same due date to the microsecond:
// one report writes them in one transaction. With a LIMIT over a set of ties
// and nothing to break them, which rows come back is the planner's choice, and
// it can differ between two ticks for reasons nothing here controls.
//
// Only fqdn assets are selected. An address is never a target of its own: it
// enters this inventory as the answer to a name, so the name is where the
// schedule belongs, and a service is observed through its host's run.
//
// @tenant: scoped
func (q *Queries) SelectDueHosts(ctx context.Context, arg SelectDueHostsParams) ([]SelectDueHostsRow, error) {
	rows, err := q.db.Query(ctx, selectDueHosts,
		arg.OrgID,
		arg.ProgramID,
		arg.Rung,
		arg.At,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDueHostsRow{}
	for rows.Next() {
		var i SelectDueHostsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Key,
			&i.Lifecycle,
			&i.BackoffTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDiscovery = `-- name: TouchDiscovery :exec
UPDATE program SET last_discovery_at = $1::timestamptz WHERE id = $2::uuid
`

type TouchDiscoveryParams struct {
	At        pgtype.Timestamptz
	ProgramID pgtype.UUID
}

// TouchDiscovery records that a discovery run was provisioned.
//
// Written at creation rather than at completion. A run that dies on the way
// must not be restarted by the cadence: the deadline sweeper already handles
// it, and confusing the two would start two.
//
// @tenant: keyed
func (q *Queries) TouchDiscovery(ctx context.Context, arg TouchDiscoveryParams) error {
	_, err := q.db.Exec(ctx, touchDiscovery, arg.At, arg.ProgramID)
	return err
}
