// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddRunTargetsParams struct {
	RunID   pgtype.UUID
	AssetID pgtype.UUID
	OrgID   pgtype.UUID
	Key     string
}

const apexesForProgram = `-- name: ApexesForProgram :many
SELECT DISTINCT pattern
  FROM scope_rule
 WHERE program_id = $1::uuid
   AND kind = 'include'
   AND matcher = 'apex'
   AND valid_from <= $2::timestamptz
   AND (valid_to IS NULL OR valid_to > $2::timestamptz)
 ORDER BY pattern
`

type ApexesForProgramParams struct {
	ProgramID pgtype.UUID
	At        pgtype.Timestamptz
}

// ApexesForProgram is a discovery run's perimeter.
func (q *Queries) ApexesForProgram(ctx context.Context, arg ApexesForProgramParams) ([]string, error) {
	rows, err := q.db.Query(ctx, apexesForProgram, arg.ProgramID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var pattern string
		if err := rows.Scan(&pattern); err != nil {
			return nil, err
		}
		items = append(items, pattern)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireRuns = `-- name: ExpireRuns :many
UPDATE run SET
    state       = 'expired',
    finished_at = $1::timestamptz,
    error       = COALESCE(error, 'the deadline passed and no report was delivered')
 WHERE state IN ('pending', 'running')
   AND deadline <= $1::timestamptz
RETURNING id, org_id, program_id, kind, scope, started_at, target_count
`

type ExpireRunsParams struct {
	At pgtype.Timestamptz
}

type ExpireRunsRow struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	ProgramID   pgtype.UUID
	Kind        string
	Scope       string
	StartedAt   pgtype.Timestamptz
	TargetCount *int32
}

// ExpireRuns is the deadline sweeper.
//
// It does not have to repair anything. Due dates are moved only when a report
// is ingested, so an abandoned run leaves the inventory exactly as it found it;
// expiring it frees its targets and makes the failure visible.
func (q *Queries) ExpireRuns(ctx context.Context, arg ExpireRunsParams) ([]ExpireRunsRow, error) {
	rows, err := q.db.Query(ctx, expireRuns, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireRunsRow{}
	for rows.Next() {
		var i ExpireRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProgramID,
			&i.Kind,
			&i.Scope,
			&i.StartedAt,
			&i.TargetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveRunForProgram = `-- name: LiveRunForProgram :one
SELECT id, kind, scope, state, deadline, created_at, started_at, target_count
  FROM run
 WHERE program_id = $1::uuid
   AND kind = $2::text
   AND state IN ('pending', 'running')
 ORDER BY created_at DESC
 LIMIT 1
`

type LiveRunForProgramParams struct {
	ProgramID pgtype.UUID
	Kind      string
}

type LiveRunForProgramRow struct {
	ID          pgtype.UUID
	Kind        string
	Scope       string
	State       string
	Deadline    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	StartedAt   pgtype.Timestamptz
	TargetCount *int32
}

// LiveRunForProgram is what a second request runs into.
//
// started_at comes back with it because it is the only thing that separates a
// run something has actually opened from one whose provisioning failed, and
// those two call for opposite actions.
func (q *Queries) LiveRunForProgram(ctx context.Context, arg LiveRunForProgramParams) (LiveRunForProgramRow, error) {
	row := q.db.QueryRow(ctx, liveRunForProgram, arg.ProgramID, arg.Kind)
	var i LiveRunForProgramRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Scope,
		&i.State,
		&i.Deadline,
		&i.CreatedAt,
		&i.StartedAt,
		&i.TargetCount,
	)
	return i, err
}

const markRunRunning = `-- name: MarkRunRunning :exec
UPDATE run SET
    state      = 'running',
    started_at = COALESCE(started_at, $1::timestamptz)
 WHERE id = $2::uuid AND state = 'pending'
`

type MarkRunRunningParams struct {
	At    pgtype.Timestamptz
	RunID pgtype.UUID
}

// MarkRunRunning records that a scanner opened the run.
func (q *Queries) MarkRunRunning(ctx context.Context, arg MarkRunRunningParams) error {
	_, err := q.db.Exec(ctx, markRunRunning, arg.At, arg.RunID)
	return err
}

const programForScheduling = `-- name: ProgramForScheduling :one
SELECT id, org_id, name, state, authorized_from, authorized_to, rate_limit_rps,
       discovery_interval, last_discovery_at, version
  FROM program
 WHERE id = $1::uuid
`

type ProgramForSchedulingParams struct {
	ProgramID pgtype.UUID
}

type ProgramForSchedulingRow struct {
	ID                pgtype.UUID
	OrgID             pgtype.UUID
	Name              string
	State             string
	AuthorizedFrom    pgtype.Timestamptz
	AuthorizedTo      pgtype.Timestamptz
	RateLimitRps      int32
	DiscoveryInterval pgtype.Interval
	LastDiscoveryAt   pgtype.Timestamptz
	Version           int32
}

// ProgramForScheduling reads what a run needs to be defined.
func (q *Queries) ProgramForScheduling(ctx context.Context, arg ProgramForSchedulingParams) (ProgramForSchedulingRow, error) {
	row := q.db.QueryRow(ctx, programForScheduling, arg.ProgramID)
	var i ProgramForSchedulingRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.State,
		&i.AuthorizedFrom,
		&i.AuthorizedTo,
		&i.RateLimitRps,
		&i.DiscoveryInterval,
		&i.LastDiscoveryAt,
		&i.Version,
	)
	return i, err
}

const programsDueForDiscovery = `-- name: ProgramsDueForDiscovery :many
SELECT p.id, p.org_id, p.name, p.rate_limit_rps
  FROM program p
 WHERE p.state = 'active'
   AND p.authorized_from <= $1::timestamptz
   AND (p.authorized_to IS NULL OR p.authorized_to > $1::timestamptz)
   AND (p.last_discovery_at IS NULL
        OR p.last_discovery_at + p.discovery_interval <= $1::timestamptz)
   -- The condition that does the work. It prevents a provisioning storm and
   -- bounds concurrency to one discovery run per programme.
   AND NOT EXISTS (
        SELECT 1 FROM run r
         WHERE r.program_id = p.id AND r.kind = 'discovery'
           AND r.state IN ('pending', 'running'))
 ORDER BY p.id
`

type ProgramsDueForDiscoveryParams struct {
	At pgtype.Timestamptz
}

type ProgramsDueForDiscoveryRow struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	Name         string
	RateLimitRps int32
}

// ProgramsDueForDiscovery is the pass that provisions enumeration.
//
// The authorization window is checked here rather than only the state. Without
// those two lines an expired programme would be provisioned on every tick and
// refused when the run opens: an execution billed to do nothing, every thirty
// seconds.
func (q *Queries) ProgramsDueForDiscovery(ctx context.Context, arg ProgramsDueForDiscoveryParams) ([]ProgramsDueForDiscoveryRow, error) {
	rows, err := q.db.Query(ctx, programsDueForDiscovery, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProgramsDueForDiscoveryRow{}
	for rows.Next() {
		var i ProgramsDueForDiscoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.RateLimitRps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runForTargets = `-- name: RunForTargets :one
SELECT r.id, r.org_id, r.program_id, r.kind, r.scope, r.state, r.deadline
  FROM run r
 WHERE r.id = $1::uuid
`

type RunForTargetsParams struct {
	RunID pgtype.UUID
}

type RunForTargetsRow struct {
	ID        pgtype.UUID
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Kind      string
	Scope     string
	State     string
	Deadline  pgtype.Timestamptz
}

// RunForTargets reads what the target list endpoint has to check.
func (q *Queries) RunForTargets(ctx context.Context, arg RunForTargetsParams) (RunForTargetsRow, error) {
	row := q.db.QueryRow(ctx, runForTargets, arg.RunID)
	var i RunForTargetsRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProgramID,
		&i.Kind,
		&i.Scope,
		&i.State,
		&i.Deadline,
	)
	return i, err
}

const selectDueHosts = `-- name: SelectDueHosts :many

SELECT c.asset_id, c.key, c.lifecycle, c.backoff_tier
  FROM asset_current c
 WHERE c.org_id = $1::uuid
   AND c.program_id = $2::uuid
   AND c.kind = 'fqdn'
   AND c.scope_status = 'in_scope'
   AND c.lifecycle <> 'archived'
   AND CASE WHEN $3::text = 'full' THEN c.next_full_at ELSE c.next_resolve_at END
       <= $4::timestamptz
   -- The lease, and the whole of it. Two runs never hold the same host, and a
   -- run that dies frees its hosts by expiring rather than by restitution.
   AND NOT EXISTS (
        SELECT 1 FROM run_target t
          JOIN run r ON r.id = t.run_id
         WHERE t.asset_id = c.asset_id
           AND r.state IN ('pending', 'running'))
 ORDER BY CASE WHEN $3::text = 'full' THEN c.next_full_at ELSE c.next_resolve_at END,
          c.asset_id
 LIMIT $5::int
`

type SelectDueHostsParams struct {
	OrgID     pgtype.UUID
	ProgramID pgtype.UUID
	Rung      string
	At        pgtype.Timestamptz
	Batch     int32
}

type SelectDueHostsRow struct {
	AssetID     pgtype.UUID
	Key         string
	Lifecycle   string
	BackoffTier int32
}

// Runs: selecting what is due, freezing it, and expiring what never delivered.
//
// There is no queue table and no lease column. Three due dates decide
// eligibility, and the frozen target list of a run is the whole of the
// reservation: selection skips what a live run already holds, and the
// reservation expires when the run does.
// SelectDueHosts is the scheduler's pass.
//
// The tiebreaker on the identity is not decoration. Assets are written in bulk,
// so thousands of rows routinely carry the same due date to the microsecond:
// one report writes them in one transaction. With a LIMIT over a set of ties
// and nothing to break them, which rows come back is the planner's choice, and
// it can differ between two ticks for reasons nothing here controls.
//
// Only fqdn assets are selected. An address is never a target of its own: it
// enters this inventory as the answer to a name, so the name is where the
// schedule belongs, and a service is observed through its host's run.
func (q *Queries) SelectDueHosts(ctx context.Context, arg SelectDueHostsParams) ([]SelectDueHostsRow, error) {
	rows, err := q.db.Query(ctx, selectDueHosts,
		arg.OrgID,
		arg.ProgramID,
		arg.Rung,
		arg.At,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDueHostsRow{}
	for rows.Next() {
		var i SelectDueHostsRow
		if err := rows.Scan(
			&i.AssetID,
			&i.Key,
			&i.Lifecycle,
			&i.BackoffTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDiscovery = `-- name: TouchDiscovery :exec
UPDATE program SET last_discovery_at = $1::timestamptz WHERE id = $2::uuid
`

type TouchDiscoveryParams struct {
	At        pgtype.Timestamptz
	ProgramID pgtype.UUID
}

// TouchDiscovery records that a discovery run was provisioned.
//
// Written at creation rather than at completion. A run that dies on the way
// must not be restarted by the cadence: the deadline sweeper already handles
// it, and confusing the two would start two.
func (q *Queries) TouchDiscovery(ctx context.Context, arg TouchDiscoveryParams) error {
	_, err := q.db.Exec(ctx, touchDiscovery, arg.At, arg.ProgramID)
	return err
}
